before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"

script:
- mkdir _build
- pdflatex -output-directory _build Studienarbeit.tex


deploy:
  provider: releases
  user: $GITHUB_USERNAME
  password: $GITHUB_PASSWORD
  file: "Studienarbeit.pdf"
  skip_cleanup: true
  on:
    tags: true
  overwrite: true

notifications:
  slack: securitysquadteam:pQQo1tevUKPZOeURc6ANrTOH
