(function(){var aa="_imgFileNameError",ba="_imgUrlTextError",ca="allHolder",da="aria-expanded",ea="bgresponse",ga="chooseWidget",ha="commentBodyField",e="complete",ia="displayModeLayout",ja="displayModeNone",h="div",ka="encodedSelectedId",m="function",la="genericOpenIdIdentityHolder",ma="goog-zippy-collapsed",na="goog-zippy-expanded",oa="hidden",pa="identity-type-",qa="identityHolder",ra="identityMenu",sa="input",ta="keypress",ua="layout-widget-description",va="layout-widget-title",wa="main-status-holder",xa=
"nameUrlIdentityHolder",n="none",ya="number",za="object",Aa="openIdIdentityHolder",Ba="openIdUriField",Ca="openIdUserNameField",Da="postCommentSubmit",Ea="ready",Fa="rotate(-45deg)",Ga="sectionWidth",Ha="select-multiple",Ia="showPreview",Ja="status-message",Ka="status-message-inner",La="subscribeButtonHolder",Ma="success",Na="true",p,Oa=typeof Object.defineProperties==m?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},Pa="undefined"!=typeof window&&window===
this?this:"undefined"!=typeof global&&null!=global?global:this,Qa=function(){Qa=function(){};Pa.Symbol||(Pa.Symbol=Ra)},Ta=0,Ra=function(a){return"jscomp_symbol_"+(a||"")+Ta++},Va=function(){Qa();var a=Pa.Symbol.iterator;a||(a=Pa.Symbol.iterator=Pa.Symbol("iterator"));typeof Array.prototype[a]!=m&&Oa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return Ua(this)}});Va=function(){}},Ua=function(a){var b=0;return Wa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})},Wa=
function(a){Va();a={next:a};a[Pa.Symbol.iterator]=function(){return this};return a},Xa=Xa||{},q=this,r=function(a){return void 0!==a},t=function(a,b,c){a=a.split(".");c=c||q;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&r(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}},Ya=function(){},Za=function(a){a.wc=void 0;a.hg=function(){return a.wc?a.wc:a.wc=new a}},$a=function(a){var b=typeof a;if(b==za)if(a){if(a instanceof Array)return"array";
if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return za;if("[object Array]"==c||typeof a.length==ya&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return m}else return"null";else if(b==m&&"undefined"==typeof a.call)return za;return b},u=function(a){return"array"==
$a(a)},ab=function(a){var b=$a(a);return"array"==b||b==za&&typeof a.length==ya},v=function(a){return"string"==typeof a},bb=function(a){return typeof a==ya},cb=function(a){return $a(a)==m},db=function(a){var b=typeof a;return b==za&&null!=a||b==m},eb="closure_uid_"+(1E9*Math.random()>>>0),fb=0,gb=function(a,b,c){return a.call.apply(a.bind,arguments)},hb=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);
Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?gb:hb;return w.apply(null,arguments)},ib=Date.now||function(){return+new Date},x=function(a,b){function c(){}c.prototype=b.prototype;a.h=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Nh=function(a,c,g){for(var d=Array(arguments.length-2),f=2;f<arguments.length;f++)d[f-2]=arguments[f];
return b.prototype[c].apply(a,d)}};var jb;var kb=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")},lb=function(a){return a.replace(/\xa0|[ \t]+/g," ")},mb=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ub=function(a,b){if(b)a=a.replace(nb,"&amp;").replace(ob,"&lt;").replace(pb,"&gt;").replace(qb,"&quot;").replace(rb,"&#39;").replace(sb,"&#0;");else{if(!tb.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(nb,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ob,"&lt;"));-1!=a.indexOf(">")&&
(a=a.replace(pb,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(qb,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(rb,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(sb,"&#0;"))}return a},nb=/&/g,ob=/</g,pb=/>/g,qb=/"/g,rb=/'/g,sb=/\x00/g,tb=/[\x00&<>"']/,vb=function(a,b){return a<b?-1:a>b?1:0};var wb=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(v(a))return v(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},xb=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(v(a))return v(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=
c;c--)if(c in a&&a[c]===b)return c;return-1},yb=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=v(a)?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},zb=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],g=0,k=v(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var y=k[l];b.call(c,y,l,a)&&(f[g++]=y)}return f},Ab=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,
b,c)}:function(a,b,c){for(var d=a.length,f=v(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return!0;return!1},Bb=function(a,b,c){a:{for(var d=a.length,f=v(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a)){b=g;break a}b=-1}return 0>b?null:v(a)?a.charAt(b):a[b]},z=function(a,b){return 0<=wb(a,b)},Cb=function(a){if(!u(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0},Db=function(a,b){b=wb(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},Eb=function(a){return Array.prototype.concat.apply([],
arguments)},Fb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Gb=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var A;a:{var Hb=q.navigator;if(Hb){var Ib=Hb.userAgent;if(Ib){A=Ib;break a}}A=""};var Jb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Kb=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Lb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Mb=function(a){for(var b in a)return!1;return!0},Nb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Ob=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<Nb.length;g++)c=Nb[g],Object.prototype.hasOwnProperty.call(d,
c)&&(a[c]=d[c])}},Pb=function(a){var b=arguments.length;if(1==b&&u(arguments[0]))return Pb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};var Qb=function(a){Qb[" "](a);return a};Qb[" "]=Ya;var Rb=function(a,b,c,d){d=d?d(b):b;return Object.prototype.hasOwnProperty.call(a,d)?a[d]:a[d]=c(b)};var Sb=-1!=A.indexOf("Opera"),B=-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"),C=-1!=A.indexOf("Edge"),D=-1!=A.indexOf("Gecko")&&!(-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"))&&!(-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"))&&-1==A.indexOf("Edge"),E=-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"),F=-1!=A.indexOf("Macintosh"),Tb=function(){var a=q.document;return a?a.documentMode:void 0},Ub;
a:{var Vb="",Wb=function(){var a=A;if(D)return/rv\:([^\);]+)(\)|;)/.exec(a);if(C)return/Edge\/([\d\.]+)/.exec(a);if(B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(E)return/WebKit\/(\S+)/.exec(a);if(Sb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Wb&&(Vb=Wb?Wb[1]:"");if(B){var Xb=Tb();if(null!=Xb&&Xb>parseFloat(Vb)){Ub=String(Xb);break a}}Ub=Vb}
var Yb=Ub,Zb={},G=function(a){return Rb(Zb,a,function(){for(var b=0,c=mb(String(Yb)).split("."),d=mb(String(a)).split("."),f=Math.max(c.length,d.length),g=0;0==b&&g<f;g++){var k=c[g]||"",l=d[g]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];l=/(\d*)(\D*)(.*)/.exec(l)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=vb(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||vb(0==k[2].length,0==l[2].length)||vb(k[2],l[2]);k=k[3];l=l[3]}while(0==b)}return 0<=b})},$b;
var ac=q.document;$b=ac&&B?Tb()||("CSS1Compat"==ac.compatMode?parseInt(Yb,10):5):void 0;var bc=!B||9<=Number($b);!D&&!B||B&&9<=Number($b)||D&&G("1.9.1");B&&G("9");var dc=function(){this.Lc="";this.rf=cc};dc.prototype.Cg=!0;var cc={};dc.prototype.Eg=function(a){this.Lc=a;return this};var ec=function(a,b){this.width=a;this.height=b};ec.prototype.clone=function(){return new ec(this.width,this.height)};ec.prototype.Mf=function(){return this.width*this.height};ec.prototype.isEmpty=function(){return!this.Mf()};ec.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var gc=function(a){return a?new fc(9==a.nodeType?a:a.ownerDocument||a.document):jb||(jb=new fc)},H=function(a){return v(a)?document.getElementById(a):a},ic=function(a,b){Jb(b,function(b,d){b&&b.Cg&&(b=b.Lc);"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:hc.hasOwnProperty(d)?a.setAttribute(hc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},hc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",
height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},kc=function(a,b,c){return jc(document,arguments)},jc=function(a,b){var c=String(b[0]),d=b[1];if(!bc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',ub(d.name),'"');if(d.type){c.push(' type="',ub(d.type),'"');var f={};Ob(f,d);delete f.type;d=f}c.push(">");c=c.join("")}c=a.createElement(c);d&&(v(d)?c.className=d:u(d)?c.className=d.join(" "):ic(c,d));2<
b.length&&lc(a,c,b,2);return c},lc=function(a,b,c,d){function f(c){c&&b.appendChild(v(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];!ab(g)||db(g)&&0<g.nodeType?f(g):yb(mc(g)?Fb(g):g,f)}},nc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},mc=function(a){if(a&&typeof a.length==ya){if(db(a))return typeof a.item==m||"string"==typeof a.item;if(cb(a))return typeof a.item==m}return!1},fc=function(a){this.oa=a||q.document||document};p=fc.prototype;
p.Pa=function(a){return v(a)?this.oa.getElementById(a):a};p.getElementsByTagName=function(a,b){return(b||this.oa).getElementsByTagName(String(a))};
p.Gd=function(a,b,c){c=c||this.oa;var d=a&&"*"!=a?String(a).toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(d||b))b=c.querySelectorAll(d+(b?"."+b:""));else if(b&&c.getElementsByClassName){var f=c.getElementsByClassName(b);if(d){c={};for(var g=a=0,k;k=f[g];g++)d==k.nodeName&&(c[a++]=k);c.length=a;b=c}else b=f}else if(f=c.getElementsByTagName(d||"*"),b){c={};for(g=a=0;k=f[g];g++)d=k.className,typeof d.split==m&&z(d.split(/\s+/),b)&&(c[a++]=k);c.length=a;b=c}else b=f;return b};
p.jc=function(a,b,c){return jc(this.oa,arguments)};p.createElement=function(a){return this.oa.createElement(String(a))};p.createTextNode=function(a){return this.oa.createTextNode(String(a))};p.appendChild=function(a,b){a.appendChild(b)};p.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var oc=function(a){return a};var I=function(){this.wa=this.wa;this.Mb=this.Mb};I.prototype.wa=!1;I.prototype.na=function(){this.wa||(this.wa=!0,this.i())};I.prototype.i=function(){if(this.Mb)for(;this.Mb.length;)this.Mb.shift()()};var pc=function(a){a&&typeof a.na==m&&a.na()};var qc=!B||9<=Number($b),rc=B&&!G("9");!E||G("528");D&&G("1.9b")||B&&G("8")||Sb&&G("9.5")||E&&G("528");D&&!G("8")||B&&G("9");var J=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.ta=!1;this.ye=!0};J.prototype.stopPropagation=function(){this.ta=!0};J.prototype.preventDefault=function(){this.defaultPrevented=!0;this.ye=!1};var K=function(a,b){J.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.ya=this.state=null;a&&this.Td(a,b)};x(K,J);
K.prototype.Td=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(D){a:{try{Qb(b.nodeName);var f=!0;break a}catch(g){}f=!1}f||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;null===d?(this.offsetX=E||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=E||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,
this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||(c==ta?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.ya=a;a.defaultPrevented&&
this.preventDefault()};K.prototype.stopPropagation=function(){K.h.stopPropagation.call(this);this.ya.stopPropagation?this.ya.stopPropagation():this.ya.cancelBubble=!0};K.prototype.preventDefault=function(){K.h.preventDefault.call(this);var a=this.ya;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,rc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var sc="closure_listenable_"+(1E6*Math.random()|0),tc=function(a){return!(!a||!a[sc])},uc=0;var vc=function(a,b,c,d,f,g){this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!f;this.yb=g;this.key=++uc;this.Ga=this.mb=!1};vc.prototype.Kb=function(){this.Ga=!0;this.yb=this.src=this.proxy=this.listener=null};var wc=function(a){this.src=a;this.o={};this.gb=0};p=wc.prototype;p.add=function(a,b,c,d,f){var g=a.toString();a=this.o[g];a||(a=this.o[g]=[],this.gb++);var k=xc(a,b,d,f);-1<k?(b=a[k],c||(b.mb=!1)):(b=new vc(b,null,this.src,g,!!d,f),b.mb=c,a.push(b));return b};p.remove=function(a,b,c,d){a=a.toString();if(!(a in this.o))return!1;var f=this.o[a];b=xc(f,b,c,d);return-1<b?(f[b].Kb(),Array.prototype.splice.call(f,b,1),0==f.length&&(delete this.o[a],this.gb--),!0):!1};
p.te=function(a){var b=a.type;if(!(b in this.o))return!1;var c=Db(this.o[b],a);c&&(a.Kb(),0==this.o[b].length&&(delete this.o[b],this.gb--));return c};p.Ob=function(a){a=a&&a.toString();var b=0,c;for(c in this.o)if(!a||c==a){for(var d=this.o[c],f=0;f<d.length;f++)++b,d[f].Kb();delete this.o[c];this.gb--}return b};p.Qa=function(a,b,c,d){a=this.o[a.toString()];var f=-1;a&&(f=xc(a,b,c,d));return-1<f?a[f]:null};
var xc=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.Ga&&g.listener==b&&g.capture==!!c&&g.yb==d)return f}return-1};var yc="closure_lm_"+(1E6*Math.random()|0),zc={},Ac=0,L=function(a,b,c,d,f){if(u(b)){for(var g=0;g<b.length;g++)L(a,b[g],c,d,f);return null}c=Bc(c);return tc(a)?a.Fa(b,c,d,f):Cc(a,b,c,!1,d,f)},Cc=function(a,b,c,d,f,g){if(!b)throw Error("Invalid event type");var k=!!f,l=Dc(a);l||(a[yc]=l=new wc(a));c=l.add(b,c,d,f,g);if(c.proxy)return c;d=Ec();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,k);else if(a.attachEvent)a.attachEvent(Fc(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");
Ac++;return c},Ec=function(){var a=Gc,b=qc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Hc=function(a,b,c,d,f){if(u(b)){for(var g=0;g<b.length;g++)Hc(a,b[g],c,d,f);return null}c=Bc(c);return tc(a)?a.Bc(b,c,d,f):Cc(a,b,c,!0,d,f)},Ic=function(a,b,c,d,f){if(u(b)){for(var g=0;g<b.length;g++)Ic(a,b[g],c,d,f);return null}c=Bc(c);if(tc(a))return a.Tb(b,c,d,f);if(!a)return!1;if(a=Dc(a))if(b=a.Qa(b,c,!!d,f))return M(b);return!1},M=function(a){if(bb(a)||
!a||a.Ga)return!1;var b=a.src;if(tc(b))return b.Qe(a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(Fc(c),d);Ac--;(c=Dc(b))?(c.te(a),0==c.gb&&(c.src=null,b[yc]=null)):a.Kb();return!0},Jc=function(a,b){if(!a)return 0;if(tc(a))return a.se(b);a=Dc(a);if(!a)return 0;var c=0;b=b&&b.toString();for(var d in a.o)if(!b||d==b)for(var f=a.o[d].concat(),g=0;g<f.length;++g)M(f[g])&&++c;return c},Fc=function(a){return a in zc?zc[a]:zc[a]="on"+a},
Lc=function(a,b,c,d){var f=!0;if(a=Dc(a))if(b=a.o[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.Ga&&(g=Kc(g,d),f=f&&!1!==g)}return f},Kc=function(a,b){var c=a.listener,d=a.yb||a.src;a.mb&&M(a);return c.call(d,b)},Gc=function(a,b){var c;if(a.Ga)return!0;if(!qc){if(!b)a:{b=["window","event"];for(var d=q;c=b.shift();)if(null!=d[c])d=d[c];else{b=null;break a}b=d}c=b;b=new K(c,this);d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=
-1;break a}catch(k){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=b.currentTarget;f;f=f.parentNode)c.push(f);a=a.type;for(var g=c.length-1;!b.ta&&0<=g;g--)b.currentTarget=c[g],f=Lc(c[g],a,!0,b),d=d&&f;for(g=0;!b.ta&&g<c.length;g++)b.currentTarget=c[g],f=Lc(c[g],a,!1,b),d=d&&f}return d}return Kc(a,new K(b,this))},Dc=function(a){a=a[yc];return a instanceof wc?a:null},Mc="__closure_events_fn_"+(1E9*Math.random()>>>0),Bc=function(a){if(cb(a))return a;a[Mc]||(a[Mc]=function(b){return a.handleEvent(b)});
return a[Mc]};var N=function(){I.call(this);this.fa=new wc(this);this.Ff=this;this.Ic=null};x(N,I);N.prototype[sc]=!0;p=N.prototype;p.addEventListener=function(a,b,c,d){L(this,a,b,c,d)};p.removeEventListener=function(a,b,c,d){Ic(this,a,b,c,d)};
p.dispatchEvent=function(a){var b=this.Ic;if(b){var c=[];for(var d=1;b;b=b.Ic)c.push(b),++d}b=this.Ff;d=a.type||a;if(v(a))a=new J(a,b);else if(a instanceof J)a.target=a.target||b;else{var f=a;a=new J(d,b);Ob(a,f)}var f=!0;if(c)for(var g=c.length-1;!a.ta&&0<=g;g--){var k=a.currentTarget=c[g];f=k.tb(d,!0,a)&&f}a.ta||(k=a.currentTarget=b,f=k.tb(d,!0,a)&&f,a.ta||(f=k.tb(d,!1,a)&&f));if(c)for(g=0;!a.ta&&g<c.length;g++)k=a.currentTarget=c[g],f=k.tb(d,!1,a)&&f;return f};
p.i=function(){N.h.i.call(this);this.se();this.Ic=null};p.Fa=function(a,b,c,d){return this.fa.add(String(a),b,!1,c,d)};p.Bc=function(a,b,c,d){return this.fa.add(String(a),b,!0,c,d)};p.Tb=function(a,b,c,d){return this.fa.remove(String(a),b,c,d)};p.Qe=function(a){return this.fa.te(a)};p.se=function(a){return this.fa?this.fa.Ob(a):0};
p.tb=function(a,b,c){a=this.fa.o[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,f=0;f<a.length;++f){var g=a[f];if(g&&!g.Ga&&g.capture==b){var k=g.listener,l=g.yb||g.src;g.mb&&this.Qe(g);d=!1!==k.call(l,c)&&d}}return d&&0!=c.ye};p.Qa=function(a,b,c,d){return this.fa.Qa(String(a),b,c,d)};var Nc="StopIteration"in q?q.StopIteration:{message:"StopIteration",stack:""},Oc=function(){};Oc.prototype.next=function(){throw Nc;};Oc.prototype.cc=function(){return this};var Pc=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},Qc=function(a){a=String(a);if(Pc(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var Rc=function(){};Rc.prototype.sd=null;Rc.prototype.Ld=function(){return this.sd||(this.sd=this.Hg())};var Sc,Tc=function(){};x(Tc,Rc);Tc.prototype.wd=function(){var a=this.Md();return a?new ActiveXObject(a):new XMLHttpRequest};Tc.prototype.Hg=function(){var a={};this.Md()&&(a[0]=!0,a[1]=!0);return a};
Tc.prototype.Md=function(){if(!this.Rd&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var a=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++){var c=a[b];try{return new ActiveXObject(c),this.Rd=c}catch(d){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return this.Rd};Sc=new Tc;var Uc=function(a,b){this.l={};this.c=[];this.hb=this.b=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};p=Uc.prototype;p.s=function(){return this.b};p.u=function(){this.pb();for(var a=[],b=0;b<this.c.length;b++)a.push(this.l[this.c[b]]);return a};p.M=function(){this.pb();return this.c.concat()};p.ma=function(a){return Vc(this.l,a)};p.isEmpty=function(){return 0==this.b};
p.clear=function(){this.l={};this.hb=this.b=this.c.length=0};p.remove=function(a){return Vc(this.l,a)?(delete this.l[a],this.b--,this.hb++,this.c.length>2*this.b&&this.pb(),!0):!1};p.pb=function(){var a,b;if(this.b!=this.c.length){for(a=b=0;b<this.c.length;){var c=this.c[b];Vc(this.l,c)&&(this.c[a++]=c);b++}this.c.length=a}if(this.b!=this.c.length){var d={};for(a=b=0;b<this.c.length;)c=this.c[b],Vc(d,c)||(this.c[a++]=c,d[c]=1),b++;this.c.length=a}};
p.get=function(a,b){return Vc(this.l,a)?this.l[a]:b};p.set=function(a,b){Vc(this.l,a)||(this.b++,this.c.push(a),this.hb++);this.l[a]=b};p.addAll=function(a){if(a instanceof Uc){var b=a.M();a=a.u()}else b=Lb(a),a=Kb(a);for(var c=0;c<b.length;c++)this.set(b[c],a[c])};p.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var f=c[d],g=this.get(f);a.call(b,g,f,this)}};p.clone=function(){return new Uc(this)};
p.cc=function(a){this.pb();var b=0,c=this.hb,d=this,f=new Oc;f.next=function(){if(c!=d.hb)throw Error("The map has changed since the iterator was created");if(b>=d.c.length)throw Nc;var f=d.c[b++];return a?f:d.l[f]};return f};var Vc=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Wc=function(a){if(a.u&&typeof a.u==m)return a.u();if(v(a))return a.split("");if(ab(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Kb(a)},Xc=function(a,b,c){if(a.forEach&&typeof a.forEach==m)a.forEach(b,c);else if(ab(a)||v(a))yb(a,b,c);else{if(a.M&&typeof a.M==m)var d=a.M();else if(a.u&&typeof a.u==m)d=void 0;else if(ab(a)||v(a)){d=[];for(var f=a.length,g=0;g<f;g++)d.push(g)}else d=Lb(a);for(var f=Wc(a),g=f.length,k=0;k<g;k++)b.call(c,f[k],d&&d[k],a)}};var Yc=function(a,b,c){if(cb(a))c&&(a=w(a,c));else if(a&&typeof a.handleEvent==m)a=w(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:q.setTimeout(a,b||0)};var Zc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,$c=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),f=null;if(0<=d){var g=a[c].substring(0,d);f=a[c].substring(d+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};var O=function(a){N.call(this);this.headers=new Uc;this.Yb=a||null;this.ba=!1;this.Xb=this.a=null;this.Ac="";this.Ea=0;this.qa=this.vc=this.Bb=this.oc=!1;this.ua=0;this.Sb=null;this.Ha="";this.Tc=this.th=this.aa=!1};x(O,N);var ad=/^https?$/i,bd=["POST","PUT"],cd=[],dd=function(a,b,c,d,f,g,k){var l=new O;cd.push(l);b&&l.Fa(e,b);l.Bc(Ea,l.Qf);g&&l.Pc(g);k&&l.Qc(k);l.send(a,c,d,f);return l};p=O.prototype;p.Qf=function(){this.na();Db(cd,this)};p.Pc=function(a){this.ua=Math.max(0,a)};
p.Bh=function(a){this.Ha=a};p.Qc=function(a){this.aa=a};
p.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request="+this.Ac+"; newUri="+a);b=b?b.toUpperCase():"GET";this.Ac=a;this.Ea=0;this.oc=!1;this.ba=!0;this.a=this.Uf();this.Xb=this.Yb?this.Yb.Ld():Sc.Ld();this.a.onreadystatechange=w(this.ne,this);this.th&&"onprogress"in this.a&&(this.a.onprogress=w(function(a){this.le(a,!0)},this),this.a.upload&&(this.a.upload.onprogress=w(this.le,this)));try{this.vc=!0,this.a.open(b,String(a),!0),this.vc=!1}catch(g){this.Ed(5,
g);return}a=c||"";var f=this.headers.clone();d&&Xc(d,function(a,b){f.set(b,a)});d=Bb(f.M(),ed);c=q.FormData&&a instanceof q.FormData;!z(bd,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Ha&&(this.a.responseType=this.Ha);"withCredentials"in this.a&&this.a.withCredentials!==this.aa&&(this.a.withCredentials=this.aa);try{this.td(),0<this.ua&&((this.Tc=fd(this.a))?(this.a.timeout=this.ua,this.a.ontimeout=
w(this.Oe,this)):this.Sb=Yc(this.Oe,this.ua,this)),this.Bb=!0,this.a.send(a),this.Bb=!1}catch(g){this.Ed(5,g)}};var fd=function(a){return B&&G(9)&&bb(a.timeout)&&r(a.ontimeout)},ed=function(a){return"content-type"==a.toLowerCase()};p=O.prototype;p.Uf=function(){return this.Yb?this.Yb.wd():Sc.wd()};p.Oe=function(){"undefined"!=typeof Xa&&this.a&&(this.Ea=8,this.dispatchEvent("timeout"),this.abort(8))};p.Ed=function(a){this.ba=!1;this.a&&(this.qa=!0,this.a.abort(),this.qa=!1);this.Ea=a;this.Bd();this.ob()};
p.Bd=function(){this.oc||(this.oc=!0,this.dispatchEvent(e),this.dispatchEvent("error"))};p.abort=function(a){this.a&&this.ba&&(this.ba=!1,this.qa=!0,this.a.abort(),this.qa=!1,this.Ea=a||7,this.dispatchEvent(e),this.dispatchEvent("abort"),this.ob())};p.i=function(){this.a&&(this.ba&&(this.ba=!1,this.qa=!0,this.a.abort(),this.qa=!1),this.ob(!0));O.h.i.call(this)};p.ne=function(){this.wa||(this.vc||this.Bb||this.qa?this.me():this.nh())};p.nh=function(){this.me()};
p.me=function(){if(this.ba&&"undefined"!=typeof Xa&&(!this.Xb[1]||4!=this.wb()||2!=this.getStatus()))if(this.Bb&&4==this.wb())Yc(this.ne,0,this);else if(this.dispatchEvent("readystatechange"),this.Jg()){this.ba=!1;try{this.Xa()?(this.dispatchEvent(e),this.dispatchEvent(Ma)):(this.Ea=6,this.Bd())}finally{this.ob()}}};p.le=function(a,b){this.dispatchEvent(gd(a,"progress"));this.dispatchEvent(gd(a,b?"downloadprogress":"uploadprogress"))};
var gd=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}};p=O.prototype;p.ob=function(a){if(this.a){this.td();var b=this.a,c=this.Xb[0]?Ya:null;this.Xb=this.a=null;a||this.dispatchEvent(Ea);try{b.onreadystatechange=c}catch(d){}}};p.td=function(){this.a&&this.Tc&&(this.a.ontimeout=null);bb(this.Sb)&&(q.clearTimeout(this.Sb),this.Sb=null)};p.Db=function(){return!!this.a};p.Jg=function(){return 4==this.wb()};
p.Xa=function(){var a=this.getStatus();a:switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var b=!0;break a;default:b=!1}return b||0===a&&!this.Kg()};p.Kg=function(){var a=String(this.Ac).match(Zc)[1]||null;!a&&q.self&&q.self.location&&(a=q.self.location.protocol,a=a.substr(0,a.length-1));return ad.test(a?a.toLowerCase():"")};p.wb=function(){return this.a?this.a.readyState:0};p.getStatus=function(){try{return 2<this.wb()?this.a.status:-1}catch(a){return-1}};
p.mg=function(){try{return this.a?this.a.responseText:""}catch(a){return""}};p.Nd=function(a){if(this.a){var b=this.a.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));return Qc(b)}};p.lg=function(){try{if(!this.a)return null;if("response"in this.a)return this.a.response;switch(this.Ha){case "":case "text":return this.a.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in this.a)return this.a.mozResponseArrayBuffer}return null}catch(a){return null}};var hd=function(){};hd.prototype.T=function(){return"NONE"};hd.prototype.N=function(){return null};var id=function(a){this.label=a};x(id,hd);id.prototype.A=function(){return this.label};var P=function(a,b){this.label=b;this.value=a.T();this.X=a};x(P,hd);P.prototype.A=function(){return this.label};P.prototype.T=function(){return this.value};P.prototype.encode=function(){return this.X.encode()+"="};P.prototype.N=function(){return new jd(this)};var Q=function(){};x(Q,hd);Q.prototype.encode=function(){return encodeURIComponent(this.T())};Q.prototype.N=function(){return null};var kd=function(a){P.call(this,a,a.A())};x(kd,P);var ld=function(){};x(ld,Q);ld.prototype.A=function(){return"Anonymous"};ld.prototype.T=function(){return"ANON"};ld.prototype.decode=function(){return new kd(this)};var md=function(a,b){this.qb=this.Uc=this.Ia="";this.Nb=null;this.ub=this.pe="";this.G=this.Lg=!1;var c;a instanceof md?(this.G=r(b)?b:a.G,this.Ie(a.Ia),this.Me(a.Uc),this.Ce(a.qb),this.Ge(a.Nb),this.setPath(a.getPath()),this.He(a.ha.clone()),this.Ee(a.ub)):a&&(c=String(a).match(Zc))?(this.G=!!b,this.Ie(c[1]||"",!0),this.Me(c[2]||"",!0),this.Ce(c[3]||"",!0),this.Ge(c[4]),this.setPath(c[5]||"",!0),this.He(c[6]||"",!0),this.Ee(c[7]||"",!0)):(this.G=!!b,this.ha=new nd(null,null,this.G))};p=md.prototype;
p.toString=function(){var a=[],b=this.Ia;b&&a.push(od(b,pd,!0),":");var c=this.qb;if(c||"file"==b)a.push("//"),(b=this.Uc)&&a.push(od(b,pd,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.Nb,null!=c&&a.push(":",String(c));if(c=this.getPath())this.yg()&&"/"!=c.charAt(0)&&a.push("/"),a.push(od(c,"/"==c.charAt(0)?qd:rd,!0));(c=this.fg())&&a.push("?",c);(c=this.ub)&&a.push("#",od(c,sd));return a.join("")};p.clone=function(){return new md(this)};
p.Ie=function(a,b){this.ea();if(this.Ia=b?td(a,!0):a)this.Ia=this.Ia.replace(/:$/,"");return this};p.Me=function(a,b){this.ea();this.Uc=b?td(a):a;return this};p.Ce=function(a,b){this.ea();this.qb=b?td(a,!0):a;return this};p.yg=function(){return!!this.qb};p.Ge=function(a){this.ea();if(a){a=Number(a);if(isNaN(a)||0>a)throw Error("Bad port number "+a);this.Nb=a}else this.Nb=null;return this};p.getPath=function(){return this.pe};p.setPath=function(a,b){this.ea();this.pe=b?td(a,!0):a;return this};
p.He=function(a,b){this.ea();a instanceof nd?(this.ha=a,this.ha.Oc(this.G)):(b||(a=od(a,ud)),this.ha=new nd(a,null,this.G));return this};p.fg=function(){return this.ha.toString()};p.Rb=function(a,b){this.ea();this.ha.set(a,b);return this};p.Ee=function(a,b){this.ea();this.ub=b?td(a):a;return this};p.ea=function(){if(this.Lg)throw Error("Tried to modify a read-only Uri");};p.Oc=function(a){this.G=a;this.ha&&this.ha.Oc(a);return this};
var td=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},od=function(a,b,c){return v(a)?(a=encodeURI(a).replace(b,vd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},vd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},pd=/[#\/\?@]/g,rd=/[\#\?:]/g,qd=/[\#\?]/g,ud=/[\#\?@]/g,sd=/#/g,nd=function(a,b,c){this.b=this.g=null;this.da=a||null;this.G=!!c};p=nd.prototype;
p.S=function(){if(!this.g&&(this.g=new Uc,this.b=0,this.da)){var a=this;$c(this.da,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)})}};p.s=function(){this.S();return this.b};p.add=function(a,b){this.S();this.Da();a=this.Aa(a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.b+=1;return this};p.remove=function(a){this.S();a=this.Aa(a);return this.g.ma(a)?(this.Da(),this.b-=this.g.get(a).length,this.g.remove(a)):!1};p.clear=function(){this.Da();this.g=null;this.b=0};
p.isEmpty=function(){this.S();return 0==this.b};p.ma=function(a){this.S();a=this.Aa(a);return this.g.ma(a)};p.forEach=function(a,b){this.S();this.g.forEach(function(c,d){yb(c,function(c){a.call(b,c,d,this)},this)},this)};p.M=function(){this.S();for(var a=this.g.u(),b=this.g.M(),c=[],d=0;d<b.length;d++)for(var f=a[d],g=0;g<f.length;g++)c.push(b[d]);return c};p.u=function(a){this.S();var b=[];if(v(a))this.ma(a)&&(b=Eb(b,this.g.get(this.Aa(a))));else{a=this.g.u();for(var c=0;c<a.length;c++)b=Eb(b,a[c])}return b};
p.set=function(a,b){this.S();this.Da();a=this.Aa(a);this.ma(a)&&(this.b-=this.g.get(a).length);this.g.set(a,[b]);this.b+=1;return this};p.get=function(a,b){a=a?this.u(a):[];return 0<a.length?String(a[0]):b};p.setValues=function(a,b){this.remove(a);0<b.length&&(this.Da(),this.g.set(this.Aa(a),Fb(b)),this.b+=b.length)};
p.toString=function(){if(this.da)return this.da;if(!this.g)return"";for(var a=[],b=this.g.M(),c=0;c<b.length;c++)for(var d=b[c],f=encodeURIComponent(String(d)),d=this.u(d),g=0;g<d.length;g++){var k=f;""!==d[g]&&(k+="="+encodeURIComponent(String(d[g])));a.push(k)}return this.da=a.join("&")};p.Da=function(){this.da=null};p.clone=function(){var a=new nd;a.da=this.da;this.g&&(a.g=this.g.clone(),a.b=this.b);return a};p.Aa=function(a){a=String(a);this.G&&(a=a.toLowerCase());return a};
p.Oc=function(a){a&&!this.G&&(this.S(),this.Da(),this.g.forEach(function(a,c){var b=c.toLowerCase();c!=b&&(this.remove(c),this.setValues(b,a))},this));this.G=a};var wd="";var xd=function(){"loading"!=document.readyState?this.Ud():L(window,"load",this.Ud)};xd.prototype.Ud=function(){var a=Array.prototype.slice.call(document.getElementsByTagName("link"),0);Va();var b=a[Symbol.iterator];a=b?b.call(a):Ua(a);for(b=a.next();!b.done;b=a.next())b=b.value,b.getAttribute("data-async-css")==Na&&b.getAttribute("media")==n&&b.setAttribute("media","all")};var yd=function(a){if(a.classList)return a.classList;a=a.className;return v(a)&&a.match(/\S+/g)||[]},zd=function(a,b){return a.classList?a.classList.contains(b):z(yd(a),b)},Ad=function(a,b){a.classList?a.classList.add(b):zd(a,b)||(a.className+=0<a.className.length?" "+b:b)},Bd=function(a,b){a.classList?a.classList.remove(b):zd(a,b)&&(a.className=zb(yd(a),function(a){return a!=b}).join(" "))};var Dd=function(a){Cd();return(new dc).Eg(a)},Cd=Ya;var Ed=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=E&&!b&&!c;if((!r(b)||d)&&a.getBoundingClientRect){a:{try{var f=a.getBoundingClientRect()}catch(g){f={left:0,top:0,right:0,bottom:0};break a}B&&a.ownerDocument.body&&(a=a.ownerDocument,f.left-=a.documentElement.clientLeft+a.body.clientLeft,f.top-=a.documentElement.clientTop+a.body.clientTop)}return new ec(f.right-f.left,f.bottom-f.top)}return new ec(b,c)},Gd=function(a,b){b=gc(b);var c=b.oa;if(B&&c.createStyleSheet){var d=c.createStyleSheet();
Fd(d,a)}else c=b.Gd("HEAD")[0],c||(d=b.Gd("BODY")[0],c=b.jc("HEAD"),d.parentNode.insertBefore(c,d)),d=b.jc("STYLE"),Fd(d,a),b.appendChild(c,d);return d},Fd=function(a,b){b instanceof dc&&b.constructor===dc&&b.rf===cc?b=b.Lc:($a(b),b="type_error:SafeStyleSheet");B&&r(a.cssText)?a.cssText=b:a.innerHTML=b};/*

 CC0 1.0 Universal License
 Public Domain Dedication

 The person(s) who associated a work with this deed has dedicated the work to
 the public domain by waiving all of his or her rights to the work worldwide
 under copyright law, including all related and neighboring rights, to the
 extent allowed by law.

 You can copy, modify, distribute and perform the work, even for commercial
 purposes, all without asking permission.

 In no way are the patent or trademark rights of any person affected by CC0,
 nor are the rights that other persons may have in the work or in how the work
 is used, such as publicity or privacy rights.

 Unless expressly stated otherwise, the person(s) who associated a work with
 this deed makes no warranties about the work, and disclaims liability for all
 uses of the work, to the fullest extent permitted by applicable law.

 When using or citing the work, you should not imply endorsement by the author
 or the affirmer.

 This is a human-readable summary of the Legal Code (read the full text).
 svg4everybody v2.0.3 | github.com/jonathantneal/svg4everybody */
var Hd=function(a){function b(a,b){if(b){var c=document.createDocumentFragment(),d=!a.getAttribute("viewBox")&&b.getAttribute("viewBox");d&&a.setAttribute("viewBox",d);for(b=b.cloneNode(!0);b.childNodes.length;)c.appendChild(b.firstChild);a.appendChild(c)}}function c(a){a.onreadystatechange=function(){if(4===a.readyState){var c=a.Ef;c||(c=a.Ef=document.implementation.createHTMLDocument(""),c.body.innerHTML=a.responseText,a.gd={});a.hd.splice(0).map(function(d){var f=a.gd[d.id];f||(f=a.gd[d.id]=c.getElementById(d.id));
b(d.Fh,f)})}};a.onreadystatechange()}(function(a){function d(){for(var a=0;a<Sd.length;){var f=Sd[a],k=f.parentNode;if(k&&/svg/i.test(k.nodeName)){var l=f.getAttribute("xlink:href");if(y&&(!g.Ih||g.Ih(l,k,f)))if(k.removeChild(f),l=l.split("#"),f=l.shift(),l=l.join("#"),f.length){var fa=Sa[f];fa||(fa=Sa[f]=new XMLHttpRequest,fa.open("GET",f),fa.send(),fa.hd=[]);fa.hd.push({Fh:k,id:l});c(fa)}else b(k,document.getElementById(l))}else++a}window.requestAnimationFrame&&window.requestAnimationFrame(d)||
setTimeout(d,67)}var g=Object(a);a=/\bTrident\/[567]\b|\bMSIE (?:9|10)\.0\b/;var k=/\bAppleWebKit\/(\d+)\b/,l=/\bEdge\/12\.(\d+)\b/;var y="polyfill"in g?g.Qh:a.test(navigator.userAgent)||10547>(navigator.userAgent.match(l)||[])[1]||537>(navigator.userAgent.match(k)||[])[1];var Sa={},Sd=document.getElementsByTagName("use");y&&d()})(a)};var Id=function(a){return/^[A-Za-z0-9]+$/.test(a)||/^#[0-9A-Fa-f]{3}$/.test(a)||/^#[0-9A-Fa-f]{6}$/.test(a)||/^rgb *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)||/^rgba *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)},Jd=function(a){a=a.split(",");for(var b=0;b<a.length;b++){var c=a[b],c=mb(c);if(!(/^[- A-Za-z0-9]*$/.test(c)||/^"[- A-Za-z0-9]*"$/.test(c)||/^'[- A-Za-z0-9]*'$/.test(c)))return!1}return!0},Kd=function(){if(window.parent&&window.parent.postMessage){var a=
document.getElementById("previewHolder"),b=0;if(a){b:{b=9==a.nodeType?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.display||b.getPropertyValue("display")||"";break b}b=""}if((b||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display)!=n)a=Ed(a);else{var b=a.style,c=b.display,d=b.visibility,f=b.position;b.visibility=oa;b.position="absolute";b.display="inline";a=Ed(a);b.display=c;b.position=f;b.visibility=
d}b=a.height}b=Math.max(b,document.body.scrollHeight);window.parent.postMessage("set-comment-editor-height "+(b||230)+"px","*")}},Ld=function(){var a=document.getElementById(ha),b=document.getElementById(Da),c=document.getElementById("postCommentPreview"),d=function(){b&&(b.disabled=""==a.value);c&&(c.disabled=""==a.value)};a&&"oninput"in a&&(d(null),L(a,sa,d))},Md=function(a){var b="";B&&(b+=".previewMode .postCommentButtonHolder { padding-top: 22px; }\n");a=(new md(a)).ub;if(0!=a.length){a=decodeURIComponent(a);
var c=Qc(a);if(c&&c.color){a=lb(kb(c.color));var d=lb(kb(c.unvisitedLinkColor)),c=lb(kb(c.fontFamily));Id(a)&&Id(d)&&Jd(c)&&(b=b+("body { color: "+a+";\nfont-family: "+c+";}\n")+("a:link, a:visited, a:active, a:hover { color: "+d+";}\n"))}}Gd(Dd(b),void 0);setTimeout(Kd,100);var f=H(ca);if((b=H(ha))&&f){var g=!1;L(b,"focus",function(){g||(g=!0,Bd(f,"compact"),Kd())})}Hd();new xd};var R=function(a){a=H(a);var b=a.nodeName.toLowerCase();a.style.display="span"==b||"img"==b||"a"==b||b==sa||"select"==b?"inline":"block"},S=function(a){H(a).style.display=n};var T=function(a,b,c){var d;c&&S(wa);switch(a){case 0:a=d="captcha-error";break;case 1:a=d="id-error";break;case 2:case 3:case 4:a="main-error";d="main-error-holder";break;case 5:a=d="nameUrlDialogErrorHolder";break;case 6:a=d="openIdDialogErrorHolder";break;case 7:a=d="genericOpenIdDialogErrorHolder";break;default:throw Error("internal error in show message");}c?(H(a).innerHTML=b,R(d),H(ha).className="commentBody-err"):(nc(H(a)),S(d));Kd()},Nd=function(a){T(3,null,!1);H("main-status").innerHTML=
a;R(wa);Kd()};var Od=function(){};Od.prototype.Eh=function(){S(ra);H(ha).disabled=!0;H(Da).disabled=!0};Od.prototype.zg=function(){R(ra);H(ha).disabled=!1;H(Da).disabled=!1};var jd=function(a){this.m=a};x(jd,Od);p=jd.prototype;p.ra=function(){return!1};p.ia=function(){if(!this.ra())throw Error("Trying to show a non-editable identity");this.Eh();R(qa)};p.Fb=function(){return!0};p.Rc=function(){if(!this.ra())throw Error("Trying to show edit button for a non-editable identity");R("editButton")};p.$a=function(){};p.cb=function(){};p.Z=function(){S(qa);S("editButton");S("settingsButton");S("commentDash");S(La);this.zg()};var Pd=function(a){a=a.className;return v(a)&&a.match(/\S+/g)||[]},Qd=function(a,b){for(var c=Pd(a),d=Gb(arguments,1),f=c.length+d.length,g=0;g<d.length;g++)z(c,d[g])||c.push(d[g]);a.className=c.join(" ");return c.length==f},Td=function(a,b){var c=Pd(a),d=Gb(arguments,1),f=Rd(c,d);a.className=f.join(" ");return f.length==c.length-d.length},Rd=function(a,b){return zb(a,function(a){return!z(b,a)})};var Wd=function(a){for(var b=[],c=Ud,d,f=a.elements,g,k=0;g=f[k];k++)if(g.form==a&&!g.disabled&&"FIELDSET"!=g.tagName)switch(d=g.name,g.type.toLowerCase()){case "file":case "submit":case "reset":case "button":break;case Ha:g=Vd(g);if(null!=g)for(var l,y=0;l=g[y];y++)c(b,d,l);break;default:l=Vd(g),null!=l&&c(b,d,l)}f=a.getElementsByTagName("INPUT");for(k=0;g=f[k];k++)g.form==a&&"image"==g.type.toLowerCase()&&(d=g.name,c(b,d,g.value),c(b,d+".x","0"),c(b,d+".y","0"));return b.join("&")},Ud=function(a,
b,c){a.push(encodeURIComponent(b)+"="+encodeURIComponent(c))},Vd=function(a){var b=a.type;if(!r(b))return null;switch(b.toLowerCase()){case "checkbox":case "radio":return a.checked?a.value:null;case "select-one":return b=a.selectedIndex,0<=b?a.options[b].value:null;case Ha:for(var b=[],c,d=0;c=a.options[d];d++)c.selected&&b.push(c.value);return b.length?b:null;default:return r(a.value)?a.value:null}};var Xd=!1,Yd=!1,Zd=!1,$d=function(a,b){Yd=a;Zd=b;window.parent==window.top&&(a||b)?(a=H(La),b?Qd(a,"checked"):Td(a,"checked"),R(La),H("ajaxAction").value=b?"UnsubscribeByEmail":"SubscribeByEmail"):S(La)};var be=function(a,b){P.call(this,new ae,a);this.eg=b};x(be,P);be.prototype.encode=function(){return this.X.encode()+"="+this.label+"="+this.eg};be.prototype.A=function(){return this.label+" (Google)"};be.prototype.N=function(){return new ce(this)};var ae=function(){};x(ae,Q);ae.prototype.A=function(){return""};ae.prototype.T=function(){return"CURRENT"};ae.prototype.decode=function(a){return new be(a[1],a[2])};ae.prototype.N=function(){throw Error("internal error");};var ce=function(a){this.m=a};
x(ce,jd);ce.prototype.Rc=function(){(Yd||Zd)&&R(La)};var de=function(a){P.call(this,a,a.A())};x(de,P);var ee=function(){};x(ee,Q);ee.prototype.A=function(){return"Google Account"};ee.prototype.T=function(){return"GOOGLE"};ee.prototype.decode=function(){return this.Kd()};ee.prototype.Kd=function(){return new de(this)};var fe=function(a,b,c){P.call(this,a,null);this.name=b;this.url=c};x(fe,P);fe.prototype.A=function(){return this.name+" ("+this.url+")"};fe.prototype.encode=function(){return this.X.encode()+"="+encodeURIComponent(this.name)+"="+encodeURIComponent(this.url)};fe.prototype.N=function(){return new ge(this)};var he=function(){};x(he,Q);he.prototype.A=function(){return"Name/URL"};he.prototype.T=function(){return"NAMEURL"};he.prototype.N=function(){return new ge(new fe(this,"",""))};
he.prototype.decode=function(a){return new fe(this,a[1],a[2])};var ge=function(a){this.m=a};x(ge,jd);p=ge.prototype;p.ra=function(){return!0};p.ia=function(){ge.h.ia.call(this);R(xa)};p.Z=function(){ge.h.Z.call(this);S(xa);T(5,null,!1);this.Fe("");this.Le("")};p.$a=function(){this.Fe(this.m.name);this.Le(this.m.url)};p.cb=function(){ge.h.cb.call(this);this.m.name=this.Jd();this.m.url=this.pg();this.Rc()};p.Fb=function(){return""==this.Jd()?(T(5,"Name should not be empty",!0),!1):!0};p.Jd=function(){return H("anonNameField").value};
p.Fe=function(a){H("anonNameField").value=a};p.pg=function(){return H("anonUrlField").value};p.Le=function(a){H("anonUrlField").value=a};var ie=function(){this.pa=[];this.Za=[];this.Ma=[];this.Ua=[];this.j=this.D=null;this.H=[]};p=ie.prototype;p.Cb=function(a,b,c,d){for(var f=0;f<this.H.length;f++)if(a==this.H[f])return d(a);d=a.encode();for(f=0;f<this.H.length;f++)if(this.H[f].encode()==d)return c(this.H[f]);return b(a)};p.Gg=function(a){return this.Cb(a,w(function(a){return this.H[this.H.length]=a},this),oc,oc)};p.Eb=function(a){function b(){return!1}return this.Cb(a,function(){return!0},b,b)};
p.Wa=function(a){function b(){throw Error("item should have been unique");}this.Cb(a,Ya,b,b);return this.Gg(a)};p.ec=function(a){return this.Cb(a,w(function(a){this.H[this.H.length]=a;return this.pa[this.pa.length]=a},this),oc,oc)};p.fe=function(){for(var a=document.getElementById("identityControlsHolder"),b=yd(a),c=0;c<b.length;c++)b[c].slice(0,14)==pa&&Bd(a,b[c]);(b=this.Ua[H(ra).selectedIndex])&&Ad(a,pa+b.value)};p.ld=function(a){this.D=this.ec(a);this.bb();this.La();this.lb(!1);return this.D};
p.la=function(a){this.Wa(a);this.Za[this.Za.length]=a};p.If=function(){var a=this.Wa(new ee);this.la(a.Kd())};p.Hf=function(){var a=new he;this.Wa(a);this.Ma[this.Ma.length]=a};p.Gf=function(){var a=this.Wa(new ld),a=this.Wa(new kd(a));this.Ma[this.Ma.length]=a};p.La=function(){var a=this.Ua[H(ra).selectedIndex];a.constructor==id?this.bb():(T(1,null,!1),this.j=a.N(),null!=this.j&&this.j.$a(),this.fe())};
p.lb=function(a){if(null!=this.j){var b=this.j.m;if(a&&this.j.ra()&&this.Eb(b)||!this.j.Fb())this.j.ia();else return this.j.cb(),this.j.Z(),this.j.ra()&&this.j.Rc(),this.j=null,b}return null};p.wh=function(){this.Vf(H("encodedIds").value);this.D=this.yd(H(ka).value);null==this.D&&0<this.pa.length&&(this.D=this.pa[0]);null==this.D&&1==this.Za.length&&(this.D=this.Za[0]);this.bb();null!=this.D&&(this.La(),this.lb(!1))};
p.md=function(a,b){this.Ua[this.Ua.length]=b;var c=document.createElement("option");c.text=b.A();c.value=b.T();try{a.add(c,null)}catch(d){a.add(c)}this.D==b&&(c.selected=!0);return c};p.fc=function(a,b){for(var c=0;c<b.length;c++)this.md(a,b[c])};p.bb=function(){for(var a=H(ra);0!=a.options.length;)a.remove(0);this.Ua=[];this.md(a,new id("Select profile...")).disabled="disabled";this.fc(a,this.pa);this.fc(a,this.Za);this.fc(a,this.Ma)};
p.ag=function(){for(var a=[],b=0;b<this.pa.length;b++)a[a.length]=this.pa[b].encode();return a.join("&")};p.Vf=function(a){if(""!=a){a=a.split("&");for(var b=0;b<a.length;b++)this.yd(a[b])}};p.yd=function(a){if(""==a)return null;a=a.split("=");for(var b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);b=this.dg(a[0]);return null!=b?(a=b.decode(a),this.ec(a)):null};p.dg=function(a){for(var b=0;b<this.H.length;b++)if(this.H[b].encode()==a)return this.H[b];return null};
p.Ue=function(){var a=H(ha).value;if(""==a)return T(2,"Comment should not be empty",!0),!1;if(1E6<a.length)return T(2,"Content length exceeds 1MB. Please abridge.",!0),!1;T(2,null,!1);return!0};p.Gc=function(){null!=this.j&&this.j.Z();this.La();var a=this.lb(!0);null!=a&&(this.D=a)};p.dh=function(){var a=this.lb(!1);null!=a&&this.ld(a)};p.bh=function(){null!=this.j&&(this.j.Z(),this.j=null);this.bb();this.Gc()};
p.oe=function(){if(null==this.D||"NONE"==this.D.T())return T(1,"Please choose a profile",!0),!1;if(null!=this.j)return!1;H("encodedIds").value=this.ag();H(ka).value=this.D.encode();return!0};p.fh=function(){this.D&&(this.La(),this.j.ia())};p.lh=function(){this.Ue()&&this.oe()&&this.Cd(!1)};p.mh=function(){this.Ue()&&this.oe()&&this.Cd(!0)};p.Cd=function(a){H(Ia).value=a?Na:"false";this.La();a=H("commentForm");a.onsubmit();a.submit()};var je=function(a,b,c,d){this.Wf=a;this.Se=b;this.name=c;this.Hh=d};x(je,Q);p=je.prototype;p.A=function(){return this.name};p.encode=function(){return encodeURIComponent(this.Wf)};p.Rf=function(a){return this.Se.replace(/{username}/,encodeURIComponent(a))};p.og=function(){return this.Se.split("{username}")};p.N=function(){return new ke(new le(this,"",""))};p.decode=function(a){return new le(this,a[1],a[2])};var le=function(a,b,c){P.call(this,a,b);this.username=c;this.uri=b;this.value="OPENID"};
x(le,P);le.prototype.A=function(){return this.username+" ("+this.X.A()+")"};le.prototype.encode=function(){return this.X.encode()+"="+encodeURIComponent(this.uri)+"="+encodeURIComponent(this.username)};le.prototype.N=function(){return new ke(this)};var ke=function(a){this.m=a};x(ke,jd);p=ke.prototype;p.ra=function(){return!0};
p.ia=function(){ke.h.ia.call(this);R(Aa);H("openIdUsernameLabel").innerHTML=this.m.X.Hh;for(var a=H(Ca),b=w(function(){this.re()},this),c=["change",ta,"keydown","keyup","blur","focus"],d=0;d<c.length;d++)L(a,c[d],b)};p.Z=function(){ke.h.Z.call(this);Jc(H(Ca));S(Aa);T(6,null,!1);H(Ba).value=""};p.$a=function(){this.Dh(this.m.username);H(Ba).value=this.m.X.Rf(this.m.username)};p.cb=function(){this.m.username=this.pc();this.$a()};
p.Fb=function(){return""==this.pc()?(T(6,"The username should not be empty",!0),!1):!0};p.re=function(){var a=this.m.X.og(),b=this.pc(),b=""==b?"username":encodeURIComponent(b);H("openIdUriDisplayPrefix").innerHTML=a[0];H("openIdUriDisplayUsername").innerHTML=b;H("openIdUriDisplaySuffix").innerHTML=a[1]};p.pc=function(){return H(Ca).value};p.Dh=function(a){H(Ca).value=a;this.re()};var me=function(){};x(me,Q);me.prototype.A=function(){return"OpenID"};me.prototype.T=function(){return"OPENID"};
me.prototype.decode=function(a){return new ne(this,a[1])};me.prototype.N=function(){return new oe(new ne(this,""))};var ne=function(a,b){P.call(this,a,b);this.uri=b;this.value="OPENID"};x(ne,P);ne.prototype.A=function(){return this.uri};ne.prototype.encode=function(){return this.X.encode()+"="+encodeURIComponent(this.uri)};ne.prototype.N=function(){return new oe(this)};var oe=function(a){this.m=a};x(oe,jd);p=oe.prototype;p.ra=function(){return!0};p.ia=function(){oe.h.ia.call(this);R(la)};
p.Z=function(){oe.h.Z.call(this);S(la);T(7,null,!1);this.Ke("")};p.$a=function(){this.Ke(this.m.uri)};p.cb=function(){this.m.uri=this.Od()};p.Fb=function(){return""==this.Od()?(T(7,"The URL should not be empty",!0),!1):!0};p.Od=function(){return H(Ba).value};p.Ke=function(a){H(Ba).value=a};var pe=function(){Td(H(ca),"previewMode");return!0};var qe;Pb("A AREA BUTTON HEAD INPUT LINK MENU META OPTGROUP OPTION PROGRESS STYLE SELECT SOURCE TEXTAREA TITLE TRACK".split(" "));var re=function(a,b,c){I.call(this);this.Cc=a;this.Ig=b||0;this.Ba=c;this.Nf=w(this.Yf,this)};x(re,I);p=re.prototype;p.Sa=0;p.i=function(){re.h.i.call(this);this.stop();delete this.Cc;delete this.Ba};p.start=function(a){this.stop();this.Sa=Yc(this.Nf,r(a)?a:this.Ig)};p.stop=function(){this.Db()&&q.clearTimeout(this.Sa);this.Sa=0};p.Db=function(){return 0!=this.Sa};p.Yf=function(){this.Sa=0;this.Cc&&this.Cc.call(this.Ba)};var se=function(a){I.call(this);this.Ba=a;this.c={}};x(se,I);var te=[];p=se.prototype;p.Fa=function(a,b,c,d){return this.Ng(a,b,c,d)};p.Ng=function(a,b,c,d,f){u(b)||(b&&(te[0]=b.toString()),b=te);for(var g=0;g<b.length;g++){var k=L(a,b[g],c||this.handleEvent,d||!1,f||this.Ba||this);if(!k)break;this.c[k.key]=k}return this};p.Bc=function(a,b,c,d){return this.ee(a,b,c,d)};
p.ee=function(a,b,c,d,f){if(u(b))for(var g=0;g<b.length;g++)this.ee(a,b[g],c,d,f);else{a=Hc(a,b,c||this.handleEvent,d,f||this.Ba||this);if(!a)return this;this.c[a.key]=a}return this};p.Tb=function(a,b,c,d,f){if(u(b))for(var g=0;g<b.length;g++)this.Tb(a,b[g],c,d,f);else c=c||this.handleEvent,f=f||this.Ba||this,c=Bc(c),d=!!d,b=tc(a)?a.Qa(b,c,d,f):a?(a=Dc(a))?a.Qa(b,c,d,f):null:null,b&&(M(b),delete this.c[b.key]);return this};
p.Ob=function(){Jb(this.c,function(a,b){this.c.hasOwnProperty(b)&&M(a)},this);this.c={}};p.i=function(){se.h.i.call(this);this.Ob()};p.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var we=function(a,b,c,d,f,g){if(!(B||C||E&&G("525")))return!0;if(F&&f)return ue(a);if(f&&!d)return!1;bb(b)&&(b=ve(b));f=17==b||18==b||F&&91==b;if((!c||F)&&f||F&&16==b&&(d||g))return!1;if((E||C)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(B&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!(E||C)}return ue(a)},ue=function(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||(E||C)&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;
default:return!1}},ve=function(a){if(D)a=xe(a);else if(F&&E)switch(a){case 93:a=91}return a},xe=function(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};var ye=function(a,b){N.call(this);a&&this.od(a,b)};x(ye,N);p=ye.prototype;p.xa=null;p.Gb=null;p.xc=null;p.Hb=null;p.I=-1;p.sa=-1;p.gc=!1;
var ze={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Ae={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Be=B||C||E&&G("525"),Ce=F&&D;p=ye.prototype;
p.vg=function(a){(E||C)&&(17==this.I&&!a.ctrlKey||18==this.I&&!a.altKey||F&&91==this.I&&!a.metaKey)&&this.we();-1==this.I&&(a.ctrlKey&&17!=a.keyCode?this.I=17:a.altKey&&18!=a.keyCode?this.I=18:a.metaKey&&91!=a.keyCode&&(this.I=91));Be&&!we(a.keyCode,this.I,a.shiftKey,a.ctrlKey,a.altKey,a.metaKey)?this.handleEvent(a):(this.sa=ve(a.keyCode),Ce&&(this.gc=a.altKey))};p.we=function(){this.sa=this.I=-1};p.wg=function(a){this.we();this.gc=a.altKey};
p.handleEvent=function(a){var b=a.ya,c=b.altKey;if(B&&a.type==ta){var d=this.sa;var f=13!=d&&27!=d?b.keyCode:0}else(E||C)&&a.type==ta?(d=this.sa,f=0<=b.charCode&&63232>b.charCode&&ue(d)?b.charCode:0):Sb&&!E?(d=this.sa,f=ue(d)?b.keyCode:0):(d=b.keyCode||this.sa,f=b.charCode||0,Ce&&(c=this.gc),F&&63==f&&224==d&&(d=191));var g=d=ve(d);d?63232<=d&&d in ze?g=ze[d]:25==d&&a.shiftKey&&(g=9):b.keyIdentifier&&b.keyIdentifier in Ae&&(g=Ae[b.keyIdentifier]);a=g==this.I;this.I=g;b=new De(g,f,a,b);b.altKey=c;
this.dispatchEvent(b)};p.Pa=function(){return this.xa};p.od=function(a,b){this.Hb&&this.detach();this.xa=a;this.Gb=L(this.xa,ta,this,b);this.xc=L(this.xa,"keydown",this.vg,b,this);this.Hb=L(this.xa,"keyup",this.wg,b,this)};p.detach=function(){this.Gb&&(M(this.Gb),M(this.xc),M(this.Hb),this.Hb=this.xc=this.Gb=null);this.xa=null;this.sa=this.I=-1};p.i=function(){ye.h.i.call(this);this.detach()};var De=function(a,b,c,d){K.call(this,d);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c};
x(De,K);var Ee={},Fe=null,Ge=function(a){a=a[eb]||(a[eb]=++fb);delete Ee[a];Mb(Ee)&&Fe&&Fe.stop()},Ie=function(){Fe||(Fe=new re(function(){He(ib())},20));var a=Fe;a.Db()||a.start()},He=function(a){Jb(Ee,function(b){b.$g(a)});Mb(Ee)||Ie()};var Je=function(){N.call(this);this.Ja=0;this.endTime=this.startTime=null};x(Je,N);p=Je.prototype;p.Ch=function(){this.Ja=1};p.Je=function(){this.Ja=0};p.Xd=function(){return 1==this.Ja};p.Wd=function(){return-1==this.Ja};p.Yd=function(){return 0==this.Ja};p.ah=function(){this.U("begin")};p.ke=function(){this.U("end")};p.hh=function(){this.U("finish")};p.kh=function(){this.U("play")};p.oh=function(){this.U("resume")};p.ph=function(){this.U("stop")};p.U=function(a){this.dispatchEvent(a)};var Ke=function(a,b,c,d){Je.call(this);if(!u(a)||!u(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.fb=a;this.cg=b;this.duration=c;this.kd=d;this.coords=[];this.progress=0};x(Ke,Je);p=Ke.prototype;
p.play=function(a){if(a||this.Yd())this.progress=0,this.coords=this.fb;else if(this.Xd())return!1;Ge(this);this.startTime=a=ib();this.Wd()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.progress||this.ah();this.kh();this.Wd()&&this.oh();this.Ch();var b=this[eb]||(this[eb]=++fb);b in Ee||(Ee[b]=this);Ie();this.xd(a);return!0};p.stop=function(a){Ge(this);this.Je();a&&(this.progress=1);this.Re(this.progress);this.ph();this.ke()};
p.i=function(){this.Yd()||this.stop(!1);this.eh();Ke.h.i.call(this)};p.$g=function(a){this.xd(a)};p.xd=function(a){a<this.startTime&&(this.endTime=a+this.endTime-this.startTime,this.startTime=a);this.progress=(a-this.startTime)/(this.endTime-this.startTime);1<this.progress&&(this.progress=1);this.Re(this.progress);1==this.progress?(this.Je(),Ge(this),this.hh(),this.ke()):this.Xd()&&this.Wg()};
p.Re=function(a){cb(this.kd)&&(a=this.kd(a));this.coords=Array(this.fb.length);for(var b=0;b<this.fb.length;b++)this.coords[b]=(this.cg[b]-this.fb[b])*a+this.fb[b]};p.Wg=function(){this.U("animate")};p.eh=function(){this.U("destroy")};p.U=function(a){this.dispatchEvent(new Le(a,this))};var Le=function(a,b){J.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.state=b.Ja};x(Le,J);var Me=function(a,b,c,d,f){function g(a){a&&(a.tabIndex=0,a.setAttribute("role","tab"),Ad(a,"goog-zippy-header"),k.$f(a),k.Zf(a))}N.call(this);this.nc=f||gc();this.ca=this.nc.Pa(a)||null;this.Oa=this.nc.Pa(d||null);this.V=(this.Jb=cb(b)?b:null)||!b?null:this.nc.Pa(b);this.W=1==c;r(c)||this.Jb||(this.Oa?this.W=this.Oa.style.display!=n:this.ca&&(this.W=zd(this.ca,na)));this.de=new se(this);this.yc=new ye;this.ie=new se(this);var k=this;g(this.ca);g(this.Oa);this.Qb(this.W)};x(Me,N);p=Me.prototype;
p.i=function(){Me.h.i.call(this);pc(this.de);pc(this.yc);pc(this.ie)};p.collapse=function(){this.Qb(!1)};p.toggle=function(){this.Qb(!this.W)};p.Qb=function(a){this.V?this.V.style.display=a?"":n:a&&this.Jb&&(this.V=this.Jb());this.V&&Ad(this.V,"goog-zippy-content");this.Oa?(this.ca.style.display=a?n:"",this.Oa.style.display=a?"":n):this.Sc(a);this.De(a);this.dispatchEvent(new Ne("toggle",this,this.W))};p.De=function(a){this.W=a};
p.Sc=function(a){if(this.ca){var b=this.ca;a?Ad(b,na):Bd(b,na);b=this.ca;a?Bd(b,ma):Ad(b,ma);b=this.ca;u(a)&&(a=a.join(" "));""===a||void 0==a?(qe||(qe={atomic:!1,autocomplete:n,dropeffect:n,haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:n,busy:!1,disabled:!1,hidden:!1,invalid:"false"}),a=qe,"expanded"in a?b.setAttribute(da,a.expanded):b.removeAttribute(da)):b.setAttribute(da,a)}};
p.Zf=function(a){a&&(this.yc.od(a),this.de.Fa(this.yc,"key",this.jh))};p.$f=function(a){a&&this.ie.Fa(a,"click",this.ih)};p.jh=function(a){if(13==a.keyCode||32==a.keyCode)this.toggle(),this.Ad(),a.preventDefault(),a.stopPropagation()};p.ih=function(){this.toggle();this.Ad()};p.Ad=function(){this.dispatchEvent(new J("action",this))};var Ne=function(a,b){J.call(this,a,b)};x(Ne,J);var Oe=function(a,b,c,d){d=d||gc();var f=d.jc("DIV",{style:"overflow:hidden"});b=d.Pa(b);b.parentNode.replaceChild(f,b);f.appendChild(b);this.rb=f;this.K=null;Me.call(this,a,b,c,void 0,d);a=this.W;this.rb.style.display=a?"":n;this.Sc(a)};x(Oe,Me);p=Oe.prototype;p.Lf=500;p.Kf=function(a){return 1-Math.pow(1-a,3)};
p.Qb=function(a){if(this.W!=a||this.K){this.rb.style.display==n&&(this.rb.style.display="");var b=this.V.offsetHeight;if(this.K){a=this.W;Jc(this.K);this.K.stop(!1);var c=b-Math.abs(parseInt(this.V.style.marginTop,10))}else c=a?0:b;this.Sc(a);this.K=new Ke([0,c],[0,a?b:0],this.Lf,this.Kf);L(this.K,["begin","animate","end"],this.Xg,!1,this);L(this.K,"begin",w(this.Yg,this,a));L(this.K,"end",w(this.Zg,this,a));this.K.play(!1)}};p.Xg=function(a){var b=this.V;b.style.marginTop=a.y-b.offsetHeight+"px"};
p.Yg=function(a){this.dispatchEvent(new Ne("a",this,a))};p.Zg=function(a){a&&(this.V.style.marginTop="0");Jc(this.K);this.De(a);this.K=null;a||(this.rb.style.display=n);this.dispatchEvent(new Ne("toggle",this,a));this.dispatchEvent(new Ne("b",this,a))};var Pe=null;var U=new ie;t("BLOG_CMT_OpenIdIdentityFactory",je,void 0);t("BLOG_CMT_LoggedInGaiaIdentity",be,void 0);t("BLOG_CMT_NotLoggedInGaiaIdentityFactory",ee,void 0);t("BLOG_CMT_GenericOpenIdIdentityFactory",me,void 0);t("BLOG_CMT_NameUrlIdentityFactory",he,void 0);t("BLOG_CMT_AnonymousIdentityFactory",ld,void 0);t("BLOG_CMT_onPost",function(){pe();return U.lh()},void 0);t("BLOG_CMT_onPreview",function(){return U.mh()},void 0);t("BLOG_CMT_onCommentBodyChange",function(){},void 0);
t("BLOG_CMT_onCancel",function(){return U.bh()},void 0);t("BLOG_CMT_onSelectorChange",function(){return U.Gc()},void 0);t("BLOG_CMT_onContinue",function(){return U.dh()},void 0);t("BLOG_CMT_onEdit",function(){return U.fh()},void 0);t("BLOG_CMT_addIdentity",function(a){return U.ec(a)},void 0);t("BLOG_CMT_addAndSelectIdentity",function(a){return U.ld(a)},void 0);t("BLOG_CMT_addIdentityFactory",function(a){return U.la(a)},void 0);t("BLOG_CMT_addNameUrlIdentityFactory",function(){return U.Hf()},void 0);
t("BLOG_CMT_addAnonIdentity",function(){return U.Gf()},void 0);t("BLOG_CMT_addNotLoggedInGaiaIdentity",function(){return U.If()},void 0);t("BLOG_CMT_init",function(a,b){Md(document.location.href);U.wh();U.Gc();U.fe();$d(a,b);H(Ia).value==Na&&(H(Ia).value="false",Qd(H(ca),"previewMode"));Ld();return!0},void 0);
t("BLOG_CMT_addOpenIdIdentityFactories",function(){U.la(new je("LJ","http://{username}.livejournal.com","LiveJournal","LiveJournal username:"));U.la(new je("WP","http://{username}.wordpress.com","WordPress","WordPress username:"));U.la(new je("TP","https://profile.typepad.com/{username}","TypePad","TypePad username:"));U.la(new je("AIM","http://openid.aol.com/{username}","AIM","AIM username:"));U.la(new me)},void 0);t("BLOG_CMT_createPhotoZippy",function(a,b){H(a)&&H(b)&&(Pe=new Oe(a,b))},void 0);
t("BLOG_CMT_closePhotoZippy",function(){null!=Pe&&Pe.collapse()},void 0);t("BLOG_CMT_finalizeBG",function(){window.qd&&window.qd.invoke(function(a){document.getElementById(ea).value=a})},void 0);
t("BLOG_CMT_getBG",function(){var a=new md("/comment-iframe-bg.g"),b=document.getElementById(ea).value;b&&a.Rb(ea,b);b=null;"Microsoft Internet Explorer"==window.navigator.appName&&(document.documentMode?b=document.documentMode:(b=5,document.compatMode&&"CSS1Compat"==document.compatMode&&(b=7)));b&&a.Rb("iemode",b);document.getElementById("pageID")&&a.Rb("page","1");wd&&a.Rb("bgint",wd);dd(a,function(){if(this.Xa()){var a=eval(this.lg());a instanceof Object&&a.length&&(1<a.length&&(eval(a[1]),wd=
a[2]),window.qd=new botguard.bg(a[0]))}})},void 0);t("BLOG_CMT_setBG",function(a){wd=a},void 0);t("BLOG_CMT_subscription.toggle",function(){if(!Xd){Xd=!0;var a=H("commentSubscriptionForm");dd(a.action,function(){Xd=!1;if(this.Xa()){var a=this.Nd();null!=a.errorMessage?T(3,a.errorMessage,!0):Nd(a.statusMessage);$d(a.can_subscribe,a.is_subscribed)}else T(3,"An error occurred while contacting the server.",!0)},"POST",Wd(a))}},void 0);t("BLOG_CMT_showStatusMessage",Nd,void 0);
t("BLOG_CMT_showPostErrorMessage",function(a){T(4,a,!0)},void 0);t("BLOG_CMT_hidePreview",function(){pe();U.bb();Kd()},void 0);t("BLOG_xhr",O,void 0);O.send=dd;O.prototype.isSuccess=O.prototype.Xa;O.prototype.getResponseJson=O.prototype.Nd;t("$",H,void 0);function Qe(a){return function(b){var c=-1;try{c=b.status}catch(d){}return 500<=c?(b.responseText.length?document.body.innerHTML=b.responseText:window.alert(LayoutsMessages.SERVER_ERROR),!1):a?a(b):!0}};var Re=function(a,b,c){var d=a.ownerDocument;b=b._GetHelper();var f=b._GetData();c._GetAllData();a=V(d,a,h,"widget-wrap1");a=V(d,a,h,"widget-wrap2");a=V(d,a,h,"widget-wrap3");var g=V(d,a,h,"widget-content");if(a=f.version&&1<f.version)g.className+=" visibility",V(d,g,h,"layout-widget-state "+(f.isVisible?"visible":"not-visible")).setAttribute("title",f.visibilityTooltipMessage);var k=V(d,g,h,"layout-title");if(f[va]){var l=V(d,g,h,ua);l.appendChild(d.createTextNode(f[va]));l.setAttribute("title",
f[ua])}k.appendChild(d.createTextNode(f["layout-title"]));var g=V(d,g,"a","editlink"),y=b._GenerateWidgetMetadata();g.setAttribute("href",y.quickEditUrl);g.target=ga;g.onclick=function(){return c._PopupConfig(d.getElementById(y.instanceId))};a&&(g.className+=" icon");g.appendChild(d.createTextNode(f["edit-link"]))},V=function(a,b,c,d){a=a.createElement(c);a.className=d;b.appendChild(a);return a};var Se=function(){this.sh={};this.he={};this.Jc={};this.Te=null;this.qe=[]};Za(Se);Se.prototype.Id=function(a,b){return a+"_"+b+".js"};var Te=function(a){eval(a)};Se.prototype.Td=function(a,b){t("__gjsload__",Te,void 0);this.Te=a.replace(/\.js$/,"");b&&(this.Id=b);yb(this.qe,function(a){this.Pg(a)},this);Cb(this.qe)};Se.prototype.uh=function(a,b,c){var d=this.he,f=this.sh;d[a]||(d[a]={});if(c)d[a][b]=c;else if(f[a]){for(b=0;b<f[a].length;++b)(0,f[a][b][1])(d[a][f[a][b][0]]);delete f[a];delete this.Jc[a]}};
Se.prototype.Pg=function(a){Yc(function(){if(!this.he[a]){var b=this.Id(this.Te,a);a:{var c=this.Jc;for(var d in c)if(c[d]==b){c=!0;break a}c=!1}this.Jc[a]=b;c||(b=kc("SCRIPT",{type:"text/javascript",src:b}),document.body.appendChild(b))}},0,this)};var Ue=function(){this.L=[];this.R=[]};p=Ue.prototype;p.Qg=function(){0==this.L.length&&(this.L=this.R,this.L.reverse(),this.R=[])};p.enqueue=function(a){this.R.push(a)};p.dequeue=function(){this.Qg();return this.L.pop()};p.s=function(){return this.L.length+this.R.length};p.isEmpty=function(){return 0==this.L.length&&0==this.R.length};p.clear=function(){this.L=[];this.R=[]};p.contains=function(a){return z(this.L,a)||z(this.R,a)};
p.remove=function(a){var b=this.L;var c=xb(b,a);0<=c?(Array.prototype.splice.call(b,c,1),b=!0):b=!1;return b||Db(this.R,a)};p.u=function(){for(var a=[],b=this.L.length-1;0<=b;--b)a.push(this.L[b]);for(var c=this.R.length,b=0;b<c;++b)a.push(this.R[b]);return a};var Ve=function(a){this.l=new Uc;a&&this.addAll(a)},We=function(a){var b=typeof a;return b==za&&a||b==m?"o"+(a[eb]||(a[eb]=++fb)):b.substr(0,1)+a};p=Ve.prototype;p.s=function(){return this.l.s()};p.add=function(a){this.l.set(We(a),a)};p.addAll=function(a){a=Wc(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};p.Ob=function(a){a=Wc(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};p.remove=function(a){return this.l.remove(We(a))};p.clear=function(){this.l.clear()};p.isEmpty=function(){return this.l.isEmpty()};
p.contains=function(a){return this.l.ma(We(a))};p.u=function(){return this.l.u()};p.clone=function(){return new Ve(this)};p.cc=function(){return this.l.cc(!1)};var Xe=function(a,b){I.call(this);this.ge=a||0;this.Lb=b||10;if(this.ge>this.Lb)throw Error("[goog.structs.Pool] Min can not be greater than max");this.Y=new Ue;this.ga=new Ve;this.delay=0;this.zc=null;this.kb()};x(Xe,I);p=Xe.prototype;p.vb=function(){var a=ib();if(!(null!=this.zc&&a-this.zc<this.delay)){var b=this.vh();b&&(this.zc=a,this.ga.add(b));return b}};p.Nc=function(a){return this.ga.remove(a)?(this.dc(a),!0):!1};
p.vh=function(){for(var a;0<this.Hd()&&(a=this.Y.dequeue(),!this.Fc(a));)this.kb();!a&&this.s()<this.Lb&&(a=this.kc());return a};p.dc=function(a){this.ga.remove(a);this.Fc(a)&&this.s()<this.Lb?this.Y.enqueue(a):this.mc(a)};p.kb=function(){for(var a=this.Y;this.s()<this.ge;)a.enqueue(this.kc());for(;this.s()>this.Lb&&0<this.Hd();)this.mc(a.dequeue())};p.kc=function(){return{}};p.mc=function(a){if(typeof a.na==m)a.na();else for(var b in a)a[b]=null};p.Fc=function(a){return typeof a.Of==m?a.Of():!0};
p.contains=function(a){return this.Y.contains(a)||this.ga.contains(a)};p.s=function(){return this.Y.s()+this.ga.s()};p.gg=function(){return this.ga.s()};p.Hd=function(){return this.Y.s()};p.isEmpty=function(){return this.Y.isEmpty()&&this.ga.isEmpty()};p.i=function(){Xe.h.i.call(this);if(0<this.gg())throw Error("[goog.structs.Pool] Objects not released");delete this.ga;for(var a=this.Y;!a.isEmpty();)this.mc(a.dequeue());delete this.Y};var Ye=function(a,b){this.ce=a;this.Wc=b};Ye.prototype.getKey=function(){return this.ce};Ye.prototype.clone=function(){return new Ye(this.ce,this.Wc)};var Ze=function(a){this.O=[];a&&this.Fg(a)};p=Ze.prototype;p.Vd=function(a,b){var c=this.O;c.push(new Ye(a,b));this.Vg(c.length-1)};p.Fg=function(a){if(a instanceof Ze){var b=a.M();a=a.u();if(0>=this.s()){for(var c=this.O,d=0;d<b.length;d++)c.push(new Ye(b[d],a[d]));return}}else b=Lb(a),a=Kb(a);for(d=0;d<b.length;d++)this.Vd(b[d],a[d])};p.remove=function(){var a=this.O,b=a.length,c=a[0];if(!(0>=b))return 1==b?Cb(a):(a[0]=a.pop(),this.Sg(0)),c.Wc};
p.Sg=function(a){for(var b=this.O,c=b.length,d=b[a];a<c>>1;){var f=this.jg(a),g=this.ng(a),f=g<c&&b[g].getKey()<b[f].getKey()?g:f;if(b[f].getKey()>d.getKey())break;b[a]=b[f];a=f}b[a]=d};p.Vg=function(a){for(var b=this.O,c=b[a];0<a;){var d=this.kg(a);if(b[d].getKey()>c.getKey())b[a]=b[d],a=d;else break}b[a]=c};p.jg=function(a){return 2*a+1};p.ng=function(a){return 2*a+2};p.kg=function(a){return a-1>>1};p.u=function(){for(var a=this.O,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].Wc);return b};
p.M=function(){for(var a=this.O,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getKey());return b};p.ma=function(a){return Ab(this.O,function(b){return b.getKey()==a})};p.clone=function(){return new Ze(this)};p.s=function(){return this.O.length};p.isEmpty=function(){return 0==this.O.length};p.clear=function(){Cb(this.O)};var $e=function(){Ze.call(this)};x($e,Ze);$e.prototype.enqueue=function(a,b){this.Vd(a,b)};$e.prototype.dequeue=function(){return this.remove()};var W=function(a,b){this.zd=void 0;this.Pb=new $e;Xe.call(this,a,b)};x(W,Xe);p=W.prototype;p.vb=function(a,b){if(!a)return(a=W.h.vb.call(this))&&this.delay&&(this.zd=q.setTimeout(w(this.xb,this),this.delay)),a;this.Pb.enqueue(r(b)?b:100,a);this.xb()};p.xb=function(){for(var a=this.Pb;0<a.s();){var b=this.vb();if(b)a.dequeue().apply(this,[b]);else break}};p.dc=function(a){W.h.dc.call(this,a);this.xb()};p.kb=function(){W.h.kb.call(this);this.xb()};
p.i=function(){W.h.i.call(this);q.clearTimeout(this.zd);this.Pb.clear();this.Pb=null};var af=function(a,b,c,d){this.rc=a;this.aa=!!d;W.call(this,b,c)};x(af,W);af.prototype.kc=function(){var a=new O,b=this.rc;b&&b.forEach(function(b,d){a.headers.set(d,b)});this.aa&&a.Qc(!0);return a};af.prototype.Fc=function(a){return!a.wa&&!a.Db()};var bf=function(a,b,c,d,f,g){N.call(this);this.Ec=r(a)?a:1;this.ua=r(f)?Math.max(0,f):0;this.aa=!!g;this.Ka=new af(b,c,d,g);this.P=new Uc;this.sb=new se(this)};x(bf,N);var cf=[Ea,e,Ma,"error","abort","timeout"];p=bf.prototype;p.Pc=function(a){this.ua=Math.max(0,a)};p.send=function(a,b,c,d,f,g,k,l,y,Sa){if(this.P.get(a))throw Error("[goog.net.XhrManager] ID in use");b=new df(b,w(this.ug,this,a),c,d,f,k,r(l)?l:this.Ec,y,r(Sa)?Sa:this.aa);this.P.set(a,b);a=w(this.rg,this,a);this.Ka.vb(a,g);return b};
p.abort=function(a,b){var c=this.P.get(a);if(c){var d=c.Vb;c.yh(!0);b&&(d&&(this.ue(d,c.Xc),Hc(d,Ea,function(){this.Ka.Nc(d)},!1,this)),this.P.remove(a));d&&d.abort()}};p.rg=function(a,b){var c=this.P.get(a);c&&!c.Vb?(this.Jf(b,c.Xc),b.Pc(this.ua),b.Bh(c.Ha),b.Qc(c.aa),c.Vb=b,this.dispatchEvent(new ef(Ea,this,a,b)),this.xe(a,b),c.jd&&b.abort()):this.Ka.Nc(b)};
p.ug=function(a,b){var c=b.target;switch(b.type){case Ea:this.xe(a,c);break;case e:return this.sg(a,c,b);case Ma:this.xg(a,c);break;case "timeout":case "error":this.tg(a,c);break;case "abort":this.qg(a,c)}return null};p.xe=function(a,b){var c=this.P.get(a);!c||c.vd||c.qc()?(c&&(this.ue(b,c.Xc),this.P.remove(a)),this.Ka.Nc(b)):(c.Dg(),b.send(c.getUrl(),c.Rg,c.getContent(),c.rc))};
p.sg=function(a,b,c){var d=this.P.get(a);if(7==b.Ea||b.Xa()||d.qc())if(this.dispatchEvent(new ef(e,this,a,b)),d&&(d.zh(!0),d.ud))return d.ud.call(b,c);return null};p.qg=function(a,b){this.dispatchEvent(new ef("abort",this,a,b))};p.xg=function(a,b){this.dispatchEvent(new ef(Ma,this,a,b))};p.tg=function(a,b){this.P.get(a).qc()&&this.dispatchEvent(new ef("error",this,a,b))};p.ue=function(a,b,c){this.sb.Tb(a,c||cf,b)};p.Jf=function(a,b,c){this.sb.Fa(a,c||cf,b)};
p.i=function(){bf.h.i.call(this);this.Ka.na();this.Ka=null;this.sb.na();this.sb=null;this.P.clear();this.P=null};var ef=function(a,b,c,d){J.call(this,a,b);this.id=c;this.Vb=d};x(ef,J);var df=function(a,b,c,d,f,g,k,l,y){this.Gh=a;this.Rg=c||"GET";this.Sf=d;this.rc=f||null;this.Ec=r(k)?k:1;this.pd=0;this.jd=this.vd=!1;this.Xc=b;this.ud=g;this.Ha=l||"";this.aa=!!y;this.Vb=null};p=df.prototype;p.getUrl=function(){return this.Gh};p.getContent=function(){return this.Sf};p.Dg=function(){this.pd++};
p.qc=function(){return this.pd>this.Ec};p.zh=function(a){this.vd=a};p.yh=function(a){this.jd=a};function ff(a,b,c,d,f,g){this.Va=a;this.Ae=b;this.ze=d||null;this.data=f||null;if(g){if(this.lc=g,"displayModeSnippet"!=g&&"displayModeFull"!=g&&g!=ia&&g!=ja)throw"bad display mode: "+g;}else this.lc=ja;this.Eb=!1}ff.prototype.ig=function(){return this.Va};function gf(a){this.Xf=!0;this.C=a;this.Ub=null}p=gf.prototype;p.Af=function(a){this.Ub=a};p.cf=function(){return this.C.data};p.vf=function(a){return this.C.data=a};p.xf=function(a){return this.C.Eb=a};
p.$e=function(){var a={};a.type=this.Ub.Pe;a.instanceId=this.C.Va;a.sectionId=this.C.Ae;a.actionUrl=X.hc;a.quickEditUrl=X.Dd+"&widgetType="+this.Ub.Pe+"&widgetId="+this.C.Va+"&sectionId="+this.C.Ae+"&action="+X.$c;return a};p.bc=function(a,b,c,d){b=b||{};window.__wavt&&(b.xssi_token=window.__wavt);X.bc(a,b,this.C.Va,this.Ub.Pe,c,d)};function X(){}X.gf=function(a,b,c){X.ja={};X.Dd=a;X.hc=b;X.Ph=c;X.Ra={};X.Wb=new bf;X.je=0;X.Kc=0;L(X.Wb,Ea,function(){X.Kc++});L(X.Wb,e,function(){X.Kc--})};
X.Cf=function(a){a=X.Xe(a.document);document.body.appendChild(a)};X.Bf=function(a){X.Cf(window);if(window.parent==window){var b="Preview";a&&(b=a);a=X.We(window.document,b);document.body.appendChild(a[0]);document.body.appendChild(a[1])}};X.jf=ga;X.Ve=ga;X.$c="editWidget";X.bf=function(){return X.hc};X.yf=function(a,b){X.Hc=a;X.rh=b};X.ef=function(){return X.Hc};X.zf=function(a){X.Jh=a};X.ad=function(){return X.Jh};X.wf=function(a){X.Ra=a};
X.af=function(){var a={},b;for(b in X.Ra){var c=X.Ra[b];a[c.name]=c.data}c={};for(b in X.ja)c[b]=X.ja[b].B.C.data;a.widgets=c;return a};X.cd=function(a,b){var c=new gf(b);a=new window[a](c);c.Af(a);X.ja[b.Va]=a;X.Zc(a);return a};X.qf=function(a,b){a=X.cd(a,b);a.B.xf(!0);return a};X.Zc=function(a){a.B.C.lc!=ja&&(a.B.Xf=!1)};X.va=function(a){return X.ja?X.ja[a]:null};
X.ac=function(a,b,c,d,f){var g="";d&&(g="&widgetId="+d);a=X.Dd+"&action="+a+"&sectionId="+b+"&widgetType="+c+g;if(window.name==f)return window.location.replace(a),window.focus(),window;f=window.open(a,f,"width=570,height=600,left=75,top=20,resizable=yes,scrollbars=yes");f.focus();return f};
X.nf=function(a){var b=a.getAttribute("id"),c=X.va(b);if(c){var d=c.B.Na;if(null!=d&&!d.closed)return d.focus(),!1}d="config"+b;a=X.ac(X.$c,a.parentNode.getAttribute("id"),a.getAttribute("widgetType"),b,d);c&&(c.B.Na=a);return!1};X.pf=function(a){X.ac(X.Ve,a.parentNode.getAttribute("id"),a.getAttribute("widgetType"),a.getAttribute("id"),X.jf);return!1};X.Ye=function(a,b,c){X.ka(c,c.LayoutsMessages.DELETING);X.ed("delete",{},a,b)};
gf.prototype.sf=function(a,b){X.ka(b,b.LayoutsMessages.SAVING);this.bc("configure",a)};X.tf=function(a,b,c){a.sectionid=document.getElementById("sectionId").value;X.ka(c,c.LayoutsMessages.SAVING);X.ed("addnew",a,"",b)};X.Mh=function(a,b,c){b=X.va(b);b.B.C.Eb?X.tf(a,c,window):b.B.sf(a,window)};X.bc=function(a,b,c,d,f,g){X.dd(X.hc,a,b,c,d,f,g)};X.ed=function(a,b,c,d,f){X.Hc&&(b.security_token=X.rh,X.dd(X.Hc,a,b,c,d,f))};
X.dd=function(a,b,c,d,f,g,k){b=["action="+encodeURIComponent(b),"widgetId="+encodeURIComponent(d),"widgetType="+encodeURIComponent(f),"responseType=js"];for(var l in c)if(typeof c[l]==za)for(d=c[l],f=0;f<d.length;++f)b.push(encodeURIComponent(l)+"="+encodeURIComponent(d[f]));else b.push(encodeURIComponent(l)+"="+encodeURIComponent(c[l]));var y=g||Qe();c=function(){y(this.a)&&window.eval(this.mg())};"GET"==k?(a=0<=a.indexOf("?")?a+"&":a+"?",X.Wb.send(""+X.je++,a+b.join("&"),"GET",void 0,null,null,
c)):X.Wb.send(""+X.je++,a,"POST",b.join("&"),null,null,c)};X.uf=function(a,b){a&&(a=X.va(a))&&(a.B.Na=b)};X.ib=function(a,b){0==X.Kc?a.setTimeout(function(){a.close()},b):a.setTimeout(function(){X.ib(a,b)},200)};X.hf=function(a,b){a&&(X.ib(a,100),X.Df(a,b))};X.Df=function(a,b){if(a){var c=a.document.getElementById(Ka);c&&(c=c.innerHTML);c&&a&&a.opener.parent&&a.opener.parent.editor&&a.opener.parent.editor.SetSaveMessage(c,b)}};
X.bd=function(a,b,c){a=X.ja[a];if(null!=c.errors){var d=a?a.B.Na:null;d||(d=window);X.ka(d,c.errors);a&&a.jb?a.jb(b,c,d):X.jb(c,d)}else a.bd(b,c)};X.jb=function(a,b){a=a["error-details"];for(var c in a)hf(c,a[c],b.document)};X.kf=function(a,b){window.parent&&window.parent.editor&&b?X.lf(a,b):window.location.replace(window.location.href)};X.lf=function(a,b){var c=X.va(a);c.B.vf(b.data);a=document.getElementById(a);nc(a);Re(a,c,X);c.B.Na=null};
X.ff=function(a,b,c){var d=c[Ja];if(null!=c.errors)X.ka(window,c.errors),X.jb(c,window);else if("addnew"==b){if(X.Zb(window)){if(window.opener&&window.opener.parent)var f=window.opener.parent;f&&f.editor&&f.editor.HandleAddNewWidget(c)}X.ka(window,d);null==window.opener?window.location="/rearrange?blogID="+c.blogID:f&&f._WidgetManager?f._WidgetManager._KillPopupDelay(window):X.ib(window,100)}else c=X.ja[a],"delete"==b&&(X.ka(c.B.Na,d),X.Ze(a,"_OnWidgetDeleted"))};
X.mf=function(a){var b=X.va(a);b&&(b.B.C.lc==ia?top.editor.HandleDeleteWidget(b.B.C.ze):(b=b.B.C.ze,b.parentNode.removeChild(b)),delete X.ja[a])};X.Ze=function(a,b,c){if(X.Zb(window)){var d=window.opener;c||(c=d._WidgetManager[b]);c(a);d._WidgetManager?d._WidgetManager._KillPopupDelay(window,a):X.ib(window,100)}else a=X.ad()+"?widgetId="+a,a+="&func="+encodeURIComponent(b),window.location.replace(a)};X.Zb=function(a){var b=!1;try{if(a.opener){var c="X"+a.opener.document.domain;c&&"X"!=c&&(b=!0)}}catch(d){}return b};
X.fd="status-msg-yellow-on-white";X.ka=function(a,b){a||(a=self);var c=a.document.getElementById(Ka);c&&(c.innerHTML=b);(a=a.document.getElementById(Ja))&&Qd(a,X.fd)};X.Kh=function(a){a||(a=self);(a=a.document.getElementById(Ja))&&Td(a,X.fd)};X.Lh=function(a){a&&0<a.length&&"http"!=a.substring(0,4)&&(a="http://"+a);return a};X.df=function(a,b){if(z(Pd(a),b))return a;if(a)for(var c=a.childNodes.length,d=0;d<c;d++){var f=X.df(a.childNodes.item(d),b);if(f)return f}return null};
X.Xe=function(a){a=a.createElement(h);a.className="blogger-clickTrap singleton-element";a.style.position="fixed";a.style.top="0";a.style.left="0";a.style.width="100%";a.style.height="100%";B&&!G(7)&&(a.style.height="expression(this.parentNode.clientHeight)");a.style.zIndex="1000";a.style.cursor="default";a.onclick=X.$b;a.onmousedown=X.$b;a.onmouseup=X.$b;a.style.background="white";a.style.filter="alpha(opacity=1)";a.style.opacity=".01";a.innerHTML="&nbsp;";return a};
X.We=function(a,b){var c=X.Yc(a,b);a=X.Yc(a,b);c.style.backgroundColor="#000";c.style.border="1px solid #aaa";B&&(c.style.filter=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678) alpha(opacity=50)');c.style.opacity=".5";a.style.border="1px solid transparent";c.style.zIndex=1200;a.style.zIndex=1200;return[c,a]};
X.Yc=function(a,b){a=a.createElement(h);a.style.position="absolute";a.style.top="75px";a.style.left="-225px";a.style.width="600px";a.style.height="28px";a.style.margin="0";a.style.padding="10px";a.style.fontSize="24px";a.style.textAlign="center";a.style.color="#fff";a.style.fontFamily='"trebuchet ms",verdana,arial,sans-serif';B&&(a.style.top="-140px",a.style.left="-140px",a.style.filter=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)');
a.style.MozTransform=Fa;a.style.MozTransformOrigin="50% 0";a.style.WebkitTransform=Fa;a.style.WebkitTransformOrigin="50% 0";a.innerHTML=b;a.className="singleton-element";return a};X.Oh=function(a){for(var b in X.Ra){var c=X.Ra[b];if(c&&"features"==c.name)return c.data[a]==Na}return!1};X.$b=function(a){a||(a=window.event);a&&(a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation());return!1};
var jf=function(a,b){b||(b=document);return b.getElementById("errormessage_"+a)},kf=function(a){if(a=jf(a))nc(a),a.className="errorbox-good"},hf=function(a,b,c){if(a=jf(a,c))a.innerHTML=b,a.className="errorbox-bad errormsg"};t("_WidgetManager",X,void 0);X._Init=X.gf;X._SetPageActionUrl=X.yf;X._GetPageActionUrl=X.ef;X._SetWidgetRefreshUrl=X.zf;X._GetWidgetRefreshUrl=X.ad;X._GetCallbackUrl=X.bf;X._DeleteWidgetFromPage=X.Ye;X._DisplayWidget=X.Zc;X._GetWidget=X.va;X._HandleControllerResult=X.bd;
X._HandlePageActionResult=X.ff;X._IsOpenerReachable=X.Zb;X._SetConfigWin=X.uf;X._SetDataContext=X.wf;X._SetupPreview=X.Bf;X._RegisterWidget=X.cd;X._RegisterNewWidget=X.qf;X._PopupPaneFromParams=X.ac;X._PopupConfig=X.nf;X._PopupToolbox=X.pf;X._KillPopupDelay=X.hf;X._OnWidgetConfigured=X.kf;X._OnWidgetDeleted=X.mf;t("_WidgetInfo",ff,void 0);ff.prototype._getInstanceId=ff.prototype.ig;gf.prototype._GetData=gf.prototype.cf;gf.prototype._GenerateWidgetMetadata=gf.prototype.$e;X._GetAllData=X.af;
t("widget_module_provide",function(a,b,c){Se.hg().uh(a,b,c)},void 0);function Y(a,b,c,d,f,g,k,l){this.F=a;this.rd="null"!=b?b:null;this.ae=c;this.Zd=d;this.$d=f;this.Be=g;this.be=k;this.xh=l;this.Ab=this.Ca=-1;this.tc=null;this.ab=300;this.Dc="200px";this.J=document.getElementById(this.F+"_picImg");this.nb=document.getElementById(this.F+"_changeImageLink");this.zb=document.getElementById(this.F+"_imageChoiceTable");this.uc=document.getElementById(this.F+"_imgSrcFromPCRadio");this.Sd=document.getElementById(this.F+"_imgSrcFromWebRadio");this.f=document.getElementById(this.F+
"_imgFileNameInput");this.Ta=document.getElementById(this.F+"_imgUrlTextInput");this.nd=window.frames[this.F+"_asynchronousFileUploadIframe"];this.sc=0;this.v=new Image;this.v.onload=w(this.qh,this);this.v.onerror=w(this.gh,this);this.Fd=!1;this.za=this.w=this.Ib=null;this.Mc=!1}p=Y.prototype;
p.qh=function(){this.sc=0;kf(this.F+ba);kf(this.F+aa);this.uc.checked&&0!=this.Ca||(this.Ca=this.v.width,this.Ab=this.v.height,this.tc=this.v.src);var a=1,b=1;this.v.width>this.ab&&(a=this.ab/this.v.width);this.v.height>this.ab&&(b=this.ab/this.v.height);a=Math.min(a,b);this.J.style.width=Math.round(this.v.width*a)+"px";this.J.style.height=Math.round(this.v.height*a)+"px";this.J.src=this.v.src;this.J.style.display="";this.zb.style.display=n;this.nb.style.display="";this.f.disabled=!0;this.ae&&this.ae.call({},
this.J.src,this.tc,this.Ca,this.Ab)};p.eb=function(a,b,c,d){a?(hf(this.F+aa,b),kf(this.F+ba)):(hf(this.F+ba,b),kf(this.F+aa));this.J.style.display=n;this.zb.style.display="";this.nb.style.display=n;this.f.disabled=!1;this.Zd&&this.Zd.call({},c,d)};p.gh=function(){if(2>this.sc){this.sc++;var a=this.v.src;this.v.src="";this.Ya(a)}else this.eb(this.uc.checked,WidgetMessages.SIV_INVALID_URL,this.J.src,[])};p.Ya=function(a){this.Ne();this.v.src=a};
p.Pf=function(a){a=a||window.event;window.event?(a.returnValue=!1,a.cancelBubble=!0):(a.preventDefault(),a.stopPropagation());this.J.style.display=n;this.nb.style.display=n;this.zb.style.display="";this.f.disabled=!1;this.Ta.value="";this.ve();this.Mc=!0;this.$d&&this.$d.call({})};p.Ag=function(){this.uc.checked=Na;this.Ta.value="";this.Ne();this.Ug();this.Fd=!0;try{this.w.submit()}catch(a){this.eb(!0,WidgetMessages.SIV_INVALID_URL,this.w.value,[])}this.Tg()};
p.ic=function(){var a=this.nd.document.result;if(a)if(a.hasErrors)0<a.errors.length?this.eb(!0,a.errors[0].message,this.f.value,a.errors):this.eb(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,a.errors);else{var b=Math.max(a.origWidth,a.origHeight),c=this.Qd();0!=this.Ca&&-1!=c&&b>c?(b=c/b,this.Ca=Math.round(a.origWidth*b),this.Ab=Math.round(a.origHeight*b)):(this.Ca=a.origWidth,this.Ab=a.origHeight);this.tc=a.mainSrc;this.Ya(a.thumbSrc)}else this.eb(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,
[])};p.Bg=function(a){9!=(a||window.event).keyCode&&(this.Sd.checked=Na,null!=this.Ib&&(window.clearTimeout(this.Ib),this.Ib=null),a=w(this.Mg,this),this.Ib=window.setTimeout(a,1E3))};p.Mg=function(){if(this.Mc||this.v.src!=this.Ta.value)this.ve(),this.Ya(this.Ta.value);this.Mc=!1};p.Og=function(a){this.Sd.checked=!0;this.Ta.value=a;this.Ya(a)};
p.Ne=function(){this.J.src="https://resources.blogblog.com/img/icon_inprogress.gif";this.J.style.width=this.Dc;this.J.style.height=this.Dc;this.J.style.display="";this.zb.style.display=n;this.nb.style.display=n};
p.Ug=function(){if(!this.w){this.w=document.createElement("form");this.w.action="imageUpload.do";this.w.method="POST";this.w.target=this.nd.name;this.w.encoding="multipart/form-data";this.w.style.display=n;if(this.rd){var a=document.createElement(sa);a.type=oa;a.name="blogID";a.value=this.rd;this.w.appendChild(a)}a=document.createElement(sa);a.type=oa;a.name=Ga;a.id=Ga;this.w.appendChild(a);a=document.createElement(sa);a.type=oa;a.name="security_token";a.value=this.xh;this.w.appendChild(a);document.body.appendChild(this.w)}a=
this.Qd();-1==a&&(a=1600);document.getElementById(Ga).value=a;this.za={parent:this.f.parentNode,nextSibling:this.f.nextSibling};this.f.parentNode.removeChild(this.f);this.w.appendChild(this.f)};p.Ah=function(a){this.ab=a;this.Dc=a+"px"};p.Tg=function(){this.w.removeChild(this.f);this.za&&this.za.nextSibling?this.za.parent.insertBefore(this.f,this.za.nextSibling):this.za.parent.appendChild(this.f)};
p.ve=function(){var a=document.createElement(sa);a.type="file";a.name=this.f.name;a.id=this.f.id;a.onchange=this.f.onchange;var b=this.f.nextSibling;null==b?this.f.parentNode.appendChild(a):this.f.parentNode.insertBefore(a,b);this.f.parentNode.removeChild(this.f);this.f=a};p.Qd=function(){return-1==this.Be&&this.be?this.be():this.Be};function Z(){this.Vc={}}var lf=new Z;Z.prototype.Tf=function(a,b,c,d,f,g,k,l){this.Vc[a]=new Y(a,b,eval(c),eval(d),eval(f),g,eval(k),l);return this.Vc[a]};
Z.prototype.Pd=function(a){return this.Vc[a]};Z.prototype.ic=function(a){(a=this.Pd(a))&&a.Fd&&a.ic()};t("_UploadSimpleImage",lf,void 0);Z.prototype._createUsiContainer=Z.prototype.Tf;Z.prototype._getUsiContainer=Z.prototype.Pd;Z.prototype._channelResultArrived=Z.prototype.ic;Y.prototype._changeImage=Y.prototype.Pf;Y.prototype._imgUrlFileOnChange=Y.prototype.Ag;Y.prototype._imgUrlTextOnKeyUp=Y.prototype.Bg;Y.prototype._loadInitialUrl=Y.prototype.Og;Y.prototype._loadImageFromUrl=Y.prototype.Ya;
Y.prototype._setPreviewSize=Y.prototype.Ah;}).call(this);
